### ISSUE TITLE
Introspection fails if SQLite database has a `references` without column name

### ISSUE THREAD

**Issue by utkarshkukreti** [drizzle-team/drizzle-kit-mirror#100]
I ran introspection on an existing large SQLite database I had and ran into an error. I finally managed to narrow it down to the fact that the error happens when there is a `references` column constraint with only a table name specified, no column name.

Here are two databases:

```
$ sqlite3 a.db .schema
CREATE TABLE users(id integer primary key);
CREATE TABLE posts(user_id integer references users);
$ sqlite3 b.db .schema
CREATE TABLE users(id integer primary key);
CREATE TABLE posts(user_id integer references users(id));
```

Introspecting `a.db` fails:

```
$ pnpm drizzle-kit introspect:sqlite --url a.db --driver better-sqlite
drizzle-kit: v0.19.2
drizzle-orm: v0.27.0

[✓] 2 tables fetched
[✓] 2 columns fetched
[✓] 0 enums fetched
[✓] 0 indexes fetched
[✓] 1 foreign keys fetched
/private/tmp/foo/node_modules/.pnpm/drizzle-kit@0.19.2/node_modules/drizzle-kit/index.cjs:36446
        return value.camelCase();
                     ^

TypeError: Cannot read properties of null (reading 'camelCase')
    at withCasing2 (/private/tmp/foo/node_modules/.pnpm/drizzle-kit@0.19.2/node_modules/drizzle-kit/index.cjs:36446:22)
    at /private/tmp/foo/node_modules/.pnpm/drizzle-kit@0.19.2/node_modules/drizzle-kit/index.cjs:36613:18
    at Array.map (<anonymous>)
    at /private/tmp/foo/node_modules/.pnpm/drizzle-kit@0.19.2/node_modules/drizzle-kit/index.cjs:36598:37
    at Array.forEach (<anonymous>)
    at createTableColumns2 (/private/tmp/foo/node_modules/.pnpm/drizzle-kit@0.19.2/node_modules/drizzle-kit/index.cjs:36591:15)
    at /private/tmp/foo/node_modules/.pnpm/drizzle-kit@0.19.2/node_modules/drizzle-kit/index.cjs:36492:22
    at Array.map (<anonymous>)
    at schemaToTypeScript2 (/private/tmp/foo/node_modules/.pnpm/drizzle-kit@0.19.2/node_modules/drizzle-kit/index.cjs:36479:61)
    at sqliteIntrospect (/private/tmp/foo/node_modules/.pnpm/drizzle-kit@0.19.2/node_modules/drizzle-kit/index.cjs:45305:18)

Node.js v18.4.0
```

while doing the same on `b.db` succeeds:

```
$ pnpm drizzle-kit introspect:sqlite --url b.db --driver better-sqlite
drizzle-kit: v0.19.2
drizzle-orm: v0.27.0

[✓] 2 tables fetched
[✓] 2 columns fetched
[✓] 0 enums fetched
[✓] 0 indexes fetched
[✓] 1 foreign keys fetched

[✓] Your SQL migration file ➜ drizzle/0000_motionless_leech.sql 🚀
[✓] You schema file is ready ➜ drizzle/schema.ts 🚀
```

I think the expected behavior is that if there is no column name, then the referenced column is the primary key column of that table.

**Comment by AndriiSherman** [comment]
Oh, never thought about this case. So never handled no columns in reference
Will patch fix this one

Thanks so much!

**Comment by rosslavery** [comment]
Just got bitten with this one while trying to migrate to Drizzle. Unfortunately we have many tables so I'm still tracking down where the rogue reference is inside our schemas 🫠

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3231.
