### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by galacoder** [drizzle-team/drizzle-kit-mirror#101]
I received an error stating "can't find module" as described in #Typescript and ESM not working together. After updating to the latest drizzle-kit, I encountered another error.

I am using a MacBook Air M1 with 16GB of RAM.

Please advise!

// Error
```
> pnpm drizzle-kit generate:pg

drizzle-kit: v0.19.2
drizzle-orm: v0.27.0

No config path provided, using default 'drizzle.config.ts'
Reading config file '/Users/galacoder/dev/action/projects/ace/packages/db/drizzle.config.ts'
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './utils' is not defined by "exports" in /Users/galacoder/dev/action/projects/ace/node_modules/drizzle-orm/package.json
    at __node_internal_captureLargerStackTrace (node:internal/errors:478:5)
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:365:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:649:3)
    at resolveExports (node:internal/modules/cjs/loader:554:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:594:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1012:27)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/galacoder/dev/action/projects/ace/node_modules/src/index.ts:70:1)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at newLoader (/Users/galacoder/dev/action/projects/ace/node_modules/drizzle-kit/index.cjs:8506:13)
    at Object.newLoader (/Users/galacoder/dev/action/projects/ace/node_modules/drizzle-kit/index.cjs:8506:13)
    at Object.extensions..js (/Users/galacoder/dev/action/projects/ace/node_modules/drizzle-kit/index.cjs:11001:28)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/Users/galacoder/dev/action/projects/ace/packages/db/src/activities/schema.ts:23:56)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Module._compile (/Users/galacoder/dev/action/projects/ace/node_modules/drizzle-kit/index.cjs:8502:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Object.newLoader [as .ts] (/Users/galacoder/dev/action/projects/ace/node_modules/drizzle-kit/index.cjs:8506:13)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at prepareFromPgImports (/Users/galacoder/dev/action/projects/ace/node_modules/drizzle-kit/index.cjs:11711:20)
    at serializePg (/Users/galacoder/dev/action/projects/ace/node_modules/drizzle-kit/index.cjs:12633:48)
    at async preparePgMigrationSnapshot (/Users/galacoder/dev/action/projects/ace/node_modules/drizzle-kit/index.cjs:12729:26)
    at async prepareAndMigratePg (/Users/galacoder/dev/action/projects/ace/node_modules/drizzle-kit/index.cjs:14110:39)
    at async Command.<anonymous> (/Users/galacoder/dev/action/projects/ace/node_modules/drizzle-kit/index.cjs:51715:3) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

My config file
```

import * as dotenv from "dotenv";

// import type { Config } from "drizzle-kit";

export default {
  schema: "./src/**/schema.ts",
  out: "./migration",
};

```

One of my schema example

```
/*
 * Activity schema
 */

import { InferModel, relations } from "drizzle-orm";
import {
  boolean,
  foreignKey,
  index,
  integer,
  json,
  pgTable,
  serial,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";

import { users } from "./../users/schema";

export const activities = pgTable(
  "activities",
  {
    id: serial("id").primaryKey(),
    _ownerId: varchar("owner_id", { length: 255 })
      .notNull()
      .references(() => users.id),
    _operatorId: text("_operator_id").references(() => users.id),
    operatedBySystem: boolean("operatedBySystem").default(false),
    category: text("category"),
    action: text("action"),
    _target: text("_target"),
    extra: json("extra"),
    createdAt: timestamp("createdAt").defaultNow(),
  },
  (table) => {
    return {
      ownerCategoryIdx: index("_owner_id_category_idx").on(table._ownerId, table.category),
      targetIdx: index("_target_idx").on(table._target),
    };
  },
);

export const activitiesRelations = relations(activities, ({ one }) => ({
  owner: one(users, {
    fields: [activities._ownerId],
    references: [users.id],
  }),
  operator: one(users, {
    fields: [activities._operatorId],
    references: [users.id],
  }),
}));

// Typing for an activity
export type Activity = InferModel<typeof activities>;
export type NewActivity = InferModel<typeof activities, "insert">;

// Schema for inserting an activity
const insertActivitySchema = createInsertSchema(activities);
// Schema for selecting an activity
const selectActivitySchema = createSelectSchema(activities);
```

**Comment by justinmpier** [comment]
Upgrading to "drizzle-orm": "0.29.1" fixed it for me

**Comment by L-Mario564** [comment]
This should be fixed in latest.
