### ISSUE TITLE
Introspect fails when directory structure is in place

### ISSUE THREAD

**Issue by jakeleventhal** [drizzle-team/drizzle-kit-mirror#112]
```
▶ npx drizzle-kit introspect:pg --driver=pg --connectionString=postgresql://postgres:local@localhost:5432/postgres

drizzle-kit: v0.19.3
drizzle-orm: v0.27.0

node:fs:599
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'drizzle/meta/_journal.json'
    at Object.openSync (node:fs:599:3)
    at readFileSync (node:fs:467:35)
    at prepareOutFolder2 (/Users/jakeleventhal/Code/rip-technologies/node_modules/.pnpm/drizzle-kit@0.19.3/node_modules/drizzle-kit/index.cjs:17765:62)
    at Command.<anonymous> (/Users/jakeleventhal/Code/rip-technologies/node_modules/.pnpm/drizzle-kit@0.19.3/node_modules/drizzle-kit/index.cjs:52367:34) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'drizzle/meta/_journal.json'
}

Node.js v18.9.1
```
```json
{
  "dependencies": {
    ...
    "drizzle-orm": "0.27.0"
  },
  "devDependencies": {
    ...
    "drizzle-kit": "0.19.3"
  }
```

this happened after i ran introspect, discarded untracked files, then ran again. the problem was that the `drizzle/meta` directory still existed. after removing that, it worked. introspect ought to handle this i think

**Comment by L-Mario564** [comment]
This should be solved in latest. If you still experience this issue after upgrading, feel free to file a new issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
