### ISSUE TITLE
drizzle studio not working well with turso dev

### ISSUE THREAD

**Issue by numso** [drizzle-team/drizzle-kit-mirror#203]
Great work on drizzle. I've been loving it so far!

If I create 2 or more tables in turso then drizzle studio will intermittently fail to load. Drizzle studio loads correctly about half the time, and errors out the other half. I've had this happen with empty tables as well as ones that have ~10 rows each. I apologize if this is the wrong place to report this; both turso and drizzle are fairly new to me.

To reproduce, run `turso dev` in one terminal and `npx drizzle-kit push:sqlite` followed by `npx drizzle-kit studio --verbose` in another. Then open up `http://localhost:4983` and refresh a bunch of times.

## Errors

Error from drizzle studio:
```
Query: select count(*) from "a"
Query: select count(*) from "b"
LibsqlError: SERVER_ERROR: Server returned HTTP status 500
    at #send (/my-project/node_modules/drizzle-kit/index.cjs:51819:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpClient.execute (/my-project/node_modules/drizzle-kit/index.cjs:51726:28)
    at PreparedQuery.all (/my-project/node_modules/src/libsql/session.ts:223:16)
    at async /my-project/node_modules/@drizzle-team/studio/index.cjs:50986:26
    at async Promise.all (index 0)
    at async Object.<anonymous> (/my-project/node_modules/@drizzle-team/studio/index.cjs:51200:17) {
  code: 'SERVER_ERROR',
  [cause]: undefined
}
```

Error from turso:
```
2023-09-30T01:37:54.415562Z ERROR sqld::error: HTTP API: 500 Internal Server Error, {"error":"Internal Error: `Error code 5: The database file is locked`"}
2023-09-30T01:37:54.415622Z ERROR tower_http::trace::on_failure: response failed classification=Status code: 500 Internal Server Error latency=1 ms
```

## Files

drizzle.config.ts
```
import type { Config } from 'drizzle-kit'
export default {
  schema: './schema.ts',
  out: './migrations',
  driver: 'turso',
  dbCredentials: { url: 'http://127.0.0.1:8080' }
} satisfies Config
```

schema.ts
```
import { integer, sqliteTable } from 'drizzle-orm/sqlite-core'
export const a = sqliteTable('a', { id: integer('id') })
export const b = sqliteTable('b', { id: integer('id') })
```

## Versions

@libsql/client: 0.3.5
drizzle-orm: 0.28.6
drizzle-kit: 0.19.13
better-sqlite3: 8.6.0

turso: v0.85.3

node: v20.7.0

**Comment by L-Mario564** [comment]
Try upgrading to latest version of ORM and Kit. Studio has improved a lot since this issue was created. If you face any new problems, feel free to open a new issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
