### ISSUE TITLE
db:generate fails: SyntaxError: Expected double-quoted property name in JSON

### ISSUE THREAD

**Issue by Mitchell-Cook-OWC** [drizzle-team/drizzle-kit-mirror#215]
I can't run `db:generate` without getting the following error

```
> drizzle-kit generate:pg

drizzle-kit: v0.19.13
drizzle-orm: v0.28.6

No config path provided, using default 'drizzle.config.ts'
Reading config file '/Users/coomitch/workspace/OWC/drizzle.config.ts'
SyntaxError: Expected double-quoted property name in JSON at position 39
    at JSON.parse (<anonymous>)
    at snapshots.reduce.malformed (/Users/coomitch/workspace/OWC/node_modules/drizzle-kit/index.cjs:18548:28)
    at Array.reduce (<anonymous>)
    at validateWithReport (/Users/coomitch/workspace/OWC/node_modules/drizzle-kit/index.cjs:18546:32)
    at prepareMigrationFolder (/Users/coomitch/workspace/OWC/node_modules/drizzle-kit/index.cjs:18588:22)
    at prepareAndMigratePg (/Users/coomitch/workspace/OWC/node_modules/drizzle-kit/index.cjs:14649:40)
    at Command.<anonymous> (/Users/coomitch/workspace/OWC/node_modules/drizzle-kit/index.cjs:53150:9)
```

Drizzle config is the below

drizzle.config.ts
```
import { cwd } from "node:process";
import type { Config } from "drizzle-kit";
import { loadEnvConfig } from "@next/env";

loadEnvConfig(cwd());

export default {
  schema: "./src/backend/db/schema.ts",
  driver: "pg",
  out: "./drizzle",
  dbCredentials: {
    connectionString: process.env.NEON_URL!,
  },
} satisfies Config;

```

**Comment by Mitchell-Cook-OWC** [comment]
Figured it out. I had some weirdness going on in my 0000_snapshot.json
