### ISSUE TITLE
Push command not working after 0.20.0

### ISSUE THREAD

**Issue by sentend** [drizzle-team/drizzle-kit-mirror#233]
im currently using drizzle-kit@0.20.2 and push command not working for pg-core with next error

```
TypeError: Cannot read properties of undefined (reading 'split')
    at Object.unsquashPK (/Users/senzu/Public/js/work/timemator/timemator_teams/backend/node_modules/.pnpm/drizzle-kit@0.20.2/node_modules/drizzle-kit/bin.cjs:4711:58)
    at /Users/senzu/Public/js/work/timemator/timemator_teams/backend/node_modules/.pnpm/drizzle-kit@0.20.2/node_modules/drizzle-kit/bin.cjs:17088:42
    at Array.map (<anonymous>)
    at prepareAddCompositePrimaryKeyPg (/Users/senzu/Public/js/work/timemator/timemator_teams/backend/node_modules/.pnpm/drizzle-kit@0.20.2/node_modules/drizzle-kit/bin.cjs:17087:33)
    at /Users/senzu/Public/js/work/timemator/timemator_teams/backend/node_modules/.pnpm/drizzle-kit@0.20.2/node_modules/drizzle-kit/bin.cjs:17523:33
    at Array.forEach (<anonymous>)
    at applySnapshotsDiff (/Users/senzu/Public/js/work/timemator/timemator_teams/backend/node_modules/.pnpm/drizzle-kit@0.20.2/node_modules/drizzle-kit/bin.cjs:17478:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async prepareSQL (/Users/senzu/Public/js/work/timemator/timemator_teams/backend/node_modules/.pnpm/drizzle-kit@0.20.2/node_modules/drizzle-kit/bin.cjs:15081:14)
    at async preparePgPush (/Users/senzu/Public/js/work/timemator/timemator_teams/backend/node_modules/.pnpm/drizzle-kit@0.20.2/node_modules/drizzle-kit/bin.cjs:14934:47)
```

with drizzle-kit 0.19.13 and drizzle-orm 0.28.6 work fine

**Comment by L-Mario564** [comment]
This should be fixed in latest. If you still experience this bug, feel free to open a new issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
