### ISSUE TITLE
Unable to generate migrations with composite key (pg, neon)

### ISSUE THREAD

**Issue by quarkstars** [drizzle-team/drizzle-kit-mirror#239]
"drizzle-kit": "^0.20.2",

Here is the schema
```
export const users = pgTable(
	"users",
	{
		id: uuid("id").defaultRandom().notNull(),
		email: varchar("email", { length: 256 }).notNull().unique(),
		name: varchar("name", { length: 256 }).notNull(),
		applicationId: uuid("application_id")
			.references(() => applications.id)
			.notNull(),
		password: varchar("password", { length: 256 }).notNull(),
		createdAt: timestamp("created_at").defaultNow().notNull(),
		updatedAt: timestamp("updated_at").defaultNow().notNull(),
	},
	(users) => {
		return {
			pk: primaryKey({ columns: [users.email, users.applicationId] }),
		};
	}
);
```
The error when running drizzle-kit generate:pg (it works when I take out the pk line)
```
TypeError: Cannot read properties of undefined (reading 'split')
    at Object.unsquashPK (S:\next-drizzle-test\node_modules\drizzle-kit\bin.cjs:4711:58)
    at S:\next-drizzle-test\node_modules\drizzle-kit\bin.cjs:17088:42
    at Array.map (<anonymous>)
    at **prepareAddCompositePrimaryKeyPg** (S:\next-drizzle-test\node_modules\drizzle-kit\bin.cjs:17087:33)
    at S:\next-drizzle-test\node_modules\drizzle-kit\bin.cjs:17523:33
    at Array.forEach (<anonymous>)
    at applySnapshotsDiff (S:\next-drizzle-test\node_modules\drizzle-kit\bin.cjs:17478:26)
    at async prepareSQL (S:\next-drizzle-test\node_modules\drizzle-kit\bin.cjs:15081:14)
    at async prepareAndMigratePg (S:\\next-drizzle-test\node_modules\drizzle-kit\bin.cjs:14851:42)
    at async Command.<anonymous> (S:\next-drizzle-test\node_modules\drizzle-kit\bin.cjs:60916:3)
```
dizzle.config.ts
```
import type { Config } from "drizzle-kit";
import { config } from "dotenv";
config({ path: ".env.local" });

export default {
	schema: "./src/**/*.schema.ts",
	driver: "pg",
	out: "./migrations",
	dbCredentials: {
		connectionString: process.env.DATABASE_URI!,
	},
} satisfies Config;

```

**Comment by pascalmtts** [comment]
We are having the same issue. The problem also exists with drizzle-kit v0.20.4

**Comment by AndriiSherman** [comment]
Taking this one

**Comment by ptts** [comment]
@AndriiSherman Thanks! 

Are there any updates on releasing DrizzleKit as OpenSource? We feel kind of powerless and really dependent on a very small circle of contributors whenever something does not work. We had 2 breaking updates within the last 2 weeks.

**Comment by MAST1999** [comment]
Isn't this similar to this issue: https://github.com/drizzle-team/drizzle-kit-mirror/issues/135

**Comment by AndriiSherman** [comment]
Fixed on `drizzle-kit@pk-issue`. Will deploy to the latest version soon. It would be great if you could check this tag.

The only potential issue here is that drizzle-kit may generate a migration that drops a primary key and recreates it one more time (not in all cases). This is because name generation was moved to the `drizzle-orm` package a few releases ago. You have two options to address this:

1. Leave this migration as is and it will rename pk in the database (recommended).
2. Simply remove those statements from the SQL file; any new generation will work fine

**Comment by AndriiSherman** [comment]
If anything won't work for you - please ping me here. Tried to test several cases, but may have missed something. Will go to latest after a few confirmations here

**Comment by pascalmtts** [comment]
Thanks! It is now working for us with `drizzle-kit@pk-issue`
