### ISSUE TITLE
Changing table name causes an error

### ISSUE THREAD

**Issue by VaniaPopovic** [drizzle-team/drizzle-kit-mirror#254]
Hey there, I'm using drizzle 0.29.0 and drizzle kit 0.20.6 connected to a planetscale database.

Im trying to run db:push

on the following schema 

```
export const users = mysqlTable("user", {
  id: varchar("id", { length: 255 }).notNull().primaryKey(),
  name: varchar("name", { length: 255 }),
  email: varchar("email", { length: 255 }).notNull(),
  emailVerified: timestamp("emailVerified", { mode: "date" }),
  registrationCompleted: boolean("registration_completed")
    .default(false)
    .notNull(),
  image: varchar("image", { length: 255 }),
  phoneNumber: varchar("phone_number", { length: 255 }),
  cvLink: varchar("cv_link", { length: 255 }),
  industries: json("industries").$type<string[]>().notNull().default([]),
  jobType: json("job_type").$type<string[]>().notNull().default([]),
});
```
renaming the from "users" to "user"

and I'm getting the following error 

```
TypeError: Cannot read properties of undefined (reading 'compositePrimaryKeys')
    at C:\Users\fream\Desktop\BOBBLL\Bobbll\node_modules\.pnpm\drizzle-kit@0.20.6\node_modules\drizzle-kit\bin.cjs:17258:51
    at Array.map (<anonymous>)
    at prepareDeleteCompositePrimaryKeyMySql (C:\Users\fream\Desktop\BOBBLL\Bobbll\node_modules\.pnpm\drizzle-kit@0.20.6\node_modules\drizzle-kit\bin.cjs:17253:33)
    at C:\Users\fream\Desktop\BOBBLL\Bobbll\node_modules\.pnpm\drizzle-kit@0.20.6\node_modules\drizzle-kit\bin.cjs:17643:33
    at Array.forEach (<anonymous>)
    at applySnapshotsDiff (C:\Users\fream\Desktop\BOBBLL\Bobbll\node_modules\.pnpm\drizzle-kit@0.20.6\node_modules\drizzle-kit\bin.cjs:17571:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async prepareSQL (C:\Users\fream\Desktop\BOBBLL\Bobbll\node_modules\.pnpm\drizzle-kit@0.20.6\node_modules\drizzle-kit\bin.cjs:15174:14)
    at async prepareMySQLPush (C:\Users\fream\Desktop\BOBBLL\Bobbll\node_modules\.pnpm\drizzle-kit@0.20.6\node_modules\drizzle-kit\bin.cjs:14974:47)
    at async Command.<anonymous> (C:\Users\fream\Desktop\BOBBLL\Bobbll\node_modules\.pnpm\drizzle-kit@0.20.6\node_modules\drizzle-kit\bin.cjs:62995:22)
```

Is this a known issue or a new one?

Kind regards,

**Comment by ryantbrown** [comment]
Is there any movement on this? It's tough because drizzle-kit source code is NA.

**Comment by matthewspear** [comment]
Also experiencing issues with this

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/2344.
