### ISSUE TITLE
BUG `drizzle-kit push:mysql` with Composite Primary Key

### ISSUE THREAD

**Issue by clburlison** [drizzle-team/drizzle-kit-mirror#271]
When you have a schema that contains a Composite Primary Key drizzle-kit is able to push the initial database creation but fails on future runs. When checking the verbose logs you can see drizzle-kit is attempting to drop all primary keys which is very similar to #216 however the compose primary key aspect is different.

<details><summary>Full Error Run</summary>
<p>

```
bun run db:push
$ drizzle-kit push:mysql
drizzle-kit: v0.20.7
drizzle-orm: v0.29.1

No config path provided, using default path
Reading config file '/Users/clayton/src/unity/drizzle-mysql-push-bug/drizzle.config.ts'
Reading schema files:
/Users/clayton/src/unity/drizzle-mysql-push-bug/schema/index.ts


 Warning  You are about to execute current statements:

CREATE TABLE `book` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` text,
	CONSTRAINT `book_id` PRIMARY KEY(`id`)
);

CREATE TABLE `books_to_authors` (
	`author_id` int NOT NULL,
	`book_id` int NOT NULL,
	CONSTRAINT `books_to_authors_book_id_author_id_pk` PRIMARY KEY(`book_id`,`author_id`)
);

CREATE TABLE `user` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` text,
	CONSTRAINT `user_id` PRIMARY KEY(`id`)
);


[✓] Changes applied
❯ bun run db:push
$ drizzle-kit push:mysql
drizzle-kit: v0.20.7
drizzle-orm: v0.29.1

No config path provided, using default path
Reading config file '/Users/clayton/src/unity/drizzle-mysql-push-bug/drizzle.config.ts'
Reading schema files:
/Users/clayton/src/unity/drizzle-mysql-push-bug/schema/index.ts


 Warning  You are about to execute current statements:

ALTER TABLE `books_to_authors` DROP PRIMARY KEY;
ALTER TABLE `books_to_authors` ADD PRIMARY KEY(`book_id`,`author_id`);
ALTER TABLE `books_to_authors` ADD PRIMARY KEY(`book_id`,`author_id`);

Error: Multiple primary key defined
    at PromiseConnection.query (/Users/clayton/src/unity/drizzle-mysql-push-bug/node_modules/drizzle-kit/bin.cjs:44278:26)
    at Command.<anonymous> (/Users/clayton/src/unity/drizzle-mysql-push-bug/node_modules/drizzle-kit/bin.cjs:63113:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ER_MULTIPLE_PRI_KEY',
  errno: 1068,
  sql: 'ALTER TABLE `books_to_authors` ADD PRIMARY KEY(`book_id`,`author_id`);',
  sqlState: '42000',
  sqlMessage: 'Multiple primary key defined'
}
```

</p>
</details> 

Reproducible repo which is just an example pulled from the docs website. https://github.com/clburlison/drizzle-mysql-push-bug.git

### Versions
drizzle-kit: v0.20.7
drizzle-orm: v0.29.1
mysql: 8.0.33

**Comment by clburlison** [comment]
Mostly user error.

This is not a good test case for what I was attempting to report. Problem with this test is that two primary keys were attempting to be assigned. Initial `drizzle-kit push` creates the database schema but secondary push failed as are two primary keys defined. Arguably this is still a bug that should be fixed but I'll leave it up to the maintainers to decide how to handle.
