### ISSUE TITLE
Postgres enum array breaks drizzle-kit commands

### ISSUE THREAD

**Issue by jakeleventhal** [drizzle-team/drizzle-kit-mirror#282]
```ts
export const AccountingAccountType = pgEnum('AccountingAccountType', [
  'COGSAssetAccount',
  'COGSExpenseAccount',
  'AdjustmentAssetAccount',
  'AdjustmentExpenseAccount',
  'CarriedBalance'
]);
```
```ts
    types: AccountingAccountType('ecominateTypes')
      .array()
      .$default(() => [])
      .notNull(),
```
When you push, it says:
>'error: type "accountingaccounttype[]" does not exist'

It seems to do all lowercase mistakenly. It works if you update the enum name to be all lowercase, but thats definitely a bug.

**Comment by skywinston** [comment]
I have also encountered this issue with the following code:

```ts
import { relations } from "drizzle-orm"
import { boolean, pgEnum, pgTable, serial, text } from "drizzle-orm/pg-core"

// pgEnum breaks on db:push — see this issue for more info:
// https://github.com/drizzle-team/drizzle-kit-mirror/issues/282
const workOsObjectTypeEnum = pgEnum("object", ["user", "organization"])

export const users = pgTable("users", {
	id: text("id").primaryKey(), // Will match the Work OS User ID
	firstName: text("first_name"),
	lastName: text("last_name"),
	email: text("email").notNull(),
	emailVerified: boolean("email_verified").notNull().default(false),
	object: workOsObjectTypeEnum("user").notNull(),
})

export const userPreferences = pgTable("user_preferences", {
	id: serial("id").primaryKey(),
	userId: text("user_id").notNull().references(() => users.id),
	expandedMenuCrm: boolean("expanded_menu_crm").notNull().default(true),
	expandedMenuTransact: boolean("expanded_menu_transact").notNull().default(true),
	pinSidebar: boolean("pin_sidebar").notNull().default(true),
})

export const usersRelations = relations(users, ({ one }) => ({
	preferences: one(userPreferences)
}))

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert
export type UserPreferences = typeof userPreferences.$inferSelect
export type NewUserPreferences = typeof userPreferences.$inferInsert
export type CurrentUserSession = User & { preferences: Omit<UserPreferences, "id" | "userId"> }
```

Then when running my `migrate` script:

```js
import { sql } from "@vercel/postgres"
import { drizzle } from "drizzle-orm/vercel-postgres"
import { migrate } from "drizzle-orm/vercel-postgres/migrator"

import "dotenv/config"

async function runMigrate() {
  if (!process.env.POSTGRES_DATABASE) {
    throw new Error("POSTGRES_DATABASE is not defined")
  }
  const db = drizzle(sql)

  console.log("Running migrations...")

  const start = Date.now()
  await migrate(db, { migrationsFolder: "app/db/migrations" })
  const end = Date.now()


  console.log(`✅ Migrations completed in ${end - start}ms`)

  process.exit(0)
}

runMigrate().catch((err) => {
  console.error("❌ Migration failed")
  console.error(err)
  process.exit(1)
})
```

The following error is printed to the console:
```sh
Running migrations...
❌ Migration failed
error: type "object" does not exist
    at /Users/skywinston/lwolf/prototypes/notifications-2/node_modules/@neondatabase/serverless/index.js:1336:74
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (/Users/skywinston/lwolf/prototypes/notifications-2/node_modules/src/pg-core/dialect.ts:72:7)
    at VercelPgSession.transaction (/Users/skywinston/lwolf/prototypes/notifications-2/node_modules/src/vercel-postgres/session.ts:147:19)
    at PgDialect.migrate (/Users/skywinston/lwolf/prototypes/notifications-2/node_modules/src/pg-core/dialect.ts:65:3)
    at migrate (/Users/skywinston/lwolf/prototypes/notifications-2/node_modules/src/vercel-postgres/migrator.ts:10:2)
    at async runMigrate (file:///Users/skywinston/lwolf/prototypes/notifications-2/app/db/migrate.js:16:3) {
  length: 94,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: '193',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_type.c',
  line: '270',
  routine: 'typenameType'
}
```
