### ISSUE TITLE
BUG: References as primary key tuple

### ISSUE THREAD

**Issue by skyf0l** [drizzle-team/drizzle-kit-mirror#306]
Here my schema:
```ts
export const tableA = mysqlTable("tableA", {
  id: int("id").primaryKey(),
});

export const tableB = mysqlTable("tableB", {
  id: int("id").primaryKey(),
});

export const tableC = mysqlTable(
  "tableC",
  {
    idA: int("idA").references(() => tableA.id, { onDelete: "cascade" }),
    idB: int("idB").references(() => tableB.id, { onDelete: "cascade" }),
  },
  (table) => {
    return {
      pk: primaryKey({ columns: [table.idA, table.idB] }),
    };
  },
);
```

I can init my schema in the database but I got error when I pushed it again:
```console
$ pnpm drizzle-kit push:mysql
drizzle-kit: v0.20.13
drizzle-orm: v0.29.3

No config path provided, using default path
Reading config file '/workspaces/monorepo/libs/database/drizzle.config.ts'
Reading schema files:
/workspaces/monorepo/libs/database/src/schema/index.ts
/workspaces/monorepo/libs/database/src/schema/relations.ts
/workspaces/monorepo/libs/database/src/schema/tables.ts

[✓] Changes applied
$ pnpm drizzle-kit push:mysql
drizzle-kit: v0.20.13
drizzle-orm: v0.29.3

No config path provided, using default path
Reading config file '/workspaces/monorepo/libs/database/drizzle.config.ts'
Reading schema files:
/workspaces/monorepo/libs/database/src/schema/index.ts
/workspaces/monorepo/libs/database/src/schema/relations.ts
/workspaces/monorepo/libs/database/src/schema/tables.ts

Error: Cannot drop index 'PRIMARY': needed in a foreign key constraint
    at PromiseConnection.query (/workspaces/monorepo/node_modules/.pnpm/drizzle-kit@0.20.13/node_modules/drizzle-kit/bin.cjs:44185:26)
    at Command.<anonymous> (/workspaces/monorepo/node_modules/.pnpm/drizzle-kit@0.20.13/node_modules/drizzle-kit/bin.cjs:63146:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ER_DROP_INDEX_FK',
  errno: 1553,
  sql: 'ALTER TABLE `tableC` DROP PRIMARY KEY;',
  sqlState: 'HY000',
  sqlMessage: "Cannot drop index 'PRIMARY': needed in a foreign key constraint"
}
```

The expected behavior was to do nothing

**Comment by skyf0l** [comment]
For now I replaced the `primaryKey` by a unique index
