### ISSUE TITLE
Drizzle studio throws error when table name contains "-"

### ISSUE THREAD

**Issue by afonsopimenta** [drizzle-team/drizzle-kit-mirror#367]
drizzle-orm version: 0.29.5
drizzle-kit version: 0.20.16
repository: [https://github.com/afonsopimenta/drizzle-studio-error](https://github.com/afonsopimenta/drizzle-studio-error)

# Error
After I upgrade drizzle-kit version to 0.20.16 `local.drizzle.studio` throws this error when page loads:
```
error: syntax error at or near "-"
    at /Users/afonsopimenta/Desktop/test/node_modules/.pnpm/drizzle-kit@0.20.16/node_modules/drizzle-kit/bin.cjs:43639:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async proxy (/Users/afonsopimenta/Desktop/test/node_modules/.pnpm/drizzle-kit@0.20.16/node_modules/drizzle-kit/bin.cjs:60358:24)
    at async /Users/afonsopimenta/Desktop/test/node_modules/.pnpm/drizzle-kit@0.20.16/node_modules/drizzle-kit/bin.cjs:60500:26
    at async dispatch (/Users/afonsopimenta/Desktop/test/node_modules/.pnpm/drizzle-kit@0.20.16/node_modules/drizzle-kit/bin.cjs:37750:21)
    at async /Users/afonsopimenta/Desktop/test/node_modules/.pnpm/drizzle-kit@0.20.16/node_modules/drizzle-kit/bin.cjs:37418:9
    at async dispatch (/Users/afonsopimenta/Desktop/test/node_modules/.pnpm/drizzle-kit@0.20.16/node_modules/drizzle-kit/bin.cjs:37750:21)
    at async cors2 (/Users/afonsopimenta/Desktop/test/node_modules/.pnpm/drizzle-kit@0.20.16/node_modules/drizzle-kit/bin.cjs:38926:9)
    at async dispatch (/Users/afonsopimenta/Desktop/test/node_modules/.pnpm/drizzle-kit@0.20.16/node_modules/drizzle-kit/bin.cjs:37750:21)
    at async /Users/afonsopimenta/Desktop/test/node_modules/.pnpm/drizzle-kit@0.20.16/node_modules/drizzle-kit/bin.cjs:38150:29 {
  length: 90,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '77',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1241',
  routine: 'scanner_yyerror'
}
```

The error occurs when I set the table prefix to something containing the character "-".
`drizzle-kit push:pg` is working fine and so is every query to the database. The issue seems to be with drizzle studio.

**Comment by RomanNabukhotnyi** [comment]
@afonsopimenta Hey! This should work now, please try it

**Comment by afonsopimenta** [comment]
> @afonsopimenta Hey! This should work now, please try it

Yeah, it works :). Thanks for the quick fix guys, keep up the great work.
Closing this issue.

**Comment by yash91989201** [comment]
@afonsopimenta  could you please tell what you did to fix it, I am facing the same issue
