### ISSUE TITLE
Drizzle studio throws after upgrade 0.20.14 --> 0.20.16

### ISSUE THREAD

**Issue by miktap** [drizzle-team/drizzle-kit-mirror#368]
drizzle-orm version: 0.30.8
drizzle-kit version: 0.20.16

# Error

After upgrading drizzle-studio from 0.20.14 to 0.20.16 (no other changes in the repository) starting Drizzle studio gives this error:

```
error: relation "public.h_vacuumhead" does not exist
    at /Users/mikkotapaninen/Desktop/Heina/heina-measurement-engine/node_modules/drizzle-kit/bin.cjs:43639:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async proxy (/Users/mikkotapaninen/Desktop/Heina/heina-measurement-engine/node_modules/drizzle-kit/bin.cjs:60358:24)
    at async /Users/mikkotapaninen/Desktop/Heina/heina-measurement-engine/node_modules/drizzle-kit/bin.cjs:60500:26
    at async dispatch (/Users/mikkotapaninen/Desktop/Heina/heina-measurement-engine/node_modules/drizzle-kit/bin.cjs:37750:21)
    at async /Users/mikkotapaninen/Desktop/Heina/heina-measurement-engine/node_modules/drizzle-kit/bin.cjs:37418:9
    at async dispatch (/Users/mikkotapaninen/Desktop/Heina/heina-measurement-engine/node_modules/drizzle-kit/bin.cjs:37750:21)
    at async cors2 (/Users/mikkotapaninen/Desktop/Heina/heina-measurement-engine/node_modules/drizzle-kit/bin.cjs:38926:9)
    at async dispatch (/Users/mikkotapaninen/Desktop/Heina/heina-measurement-engine/node_modules/drizzle-kit/bin.cjs:37750:21)
    at async /Users/mikkotapaninen/Desktop/Heina/heina-measurement-engine/node_modules/drizzle-kit/bin.cjs:38150:29 {
  length: 119,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '139',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1355',
  routine: 'parserOpenTable'
}
```

The schema (which I have introspected with drizzle-kit) has not changed and Drizzle studio worked well with version 0.20.14.

This is especially annoying as upgrade from 0.20.14 to 0.20.16 was forced and I can't use 0.20.14 anymore 😢

**Comment by RomanNabukhotnyi** [comment]
@miktap Hey! Can you please share your schema?

**Comment by miktap** [comment]
Now it works again, perhaps it was related to #367 . Closing the issue.
