### ISSUE TITLE
Drizzle studio keeps crashing when I using mysql2 driver

### ISSUE THREAD

**Issue by Keith-Web3** [drizzle-team/drizzle-kit-mirror#386]
I'm using the mysql2 driver for my drizzle setup. Whenever I try to run the Drizzle Studio, it runs and gives the studio url: `https://local.drizzle.studio` but when I navigate to the link, I get an error in my terminal and the drizzle studio just keeps loading indefinitely. Here's the error I got:
```bash
Error: connect ETIMEDOUT
    at PromisePool.query (C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:60148:26)
    at proxy (C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:60483:37)        
    at C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:60628:32
    at dispatch (C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:37750:27)     
    at C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:37751:24
    at C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:37418:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async dispatch (C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:37750:21)
    at async cors2 (C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:38926:9)   
    at async dispatch (C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:37750:21) {
  code: 'ETIMEDOUT',
  errno: undefined,
  sql: undefined,
  sqlState: undefined,
  sqlMessage: undefined
}
Error: connect ETIMEDOUT
    at PromisePool.query (C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:60148:26)
    at proxy (C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:60483:37)        
    at C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:60628:32
    at dispatch (C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:37750:27)     
    at C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:37751:24
    at C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:37418:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async cors2 (C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:38926:9)        
    at async dispatch (C:\Users\Doyin\Desktop\drizzle-sql\start\node_modules\drizzle-kit\bin.cjs:37750:21) {  
  code: 'ETIMEDOUT',
  errno: undefined,
  sql: undefined,
  sqlState: undefined,
  sqlMessage: undefined
}
```

**Comment by AlexBlokh** [comment]
I'm not sure it's drizzle-kit responsible, since we're just using `mysql2` driver
you should reproduce the issue in `ts` or `js` script and if there's any issue(which I doubt, mysql2 is an industry grade library) - file it in their repo

I suppose you just have either database setup or credentials wrong

**Comment by Keith-Web3** [comment]
Alright, I'm working on something else right now but I'll check back on it
