### ISSUE TITLE
Cannot run migration with sound [mysql] SQL (?)

### ISSUE THREAD

**Issue by NicholasFields** [drizzle-team/drizzle-kit-mirror#39]
Error ::

```
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `joiner_table` (
`id` serial AUTO_INCREMENT PRIMARY KEY NOT NULL,
' at line 6
at query (/workspaces/amni-sst/node_modules/.pnpm/mysql2@2.3.3/node_modules/mysql2/promise.js:93:22)
at async (/workspaces/amni-sst/node_modules/.pnpm/drizzle-orm@0.25.3_@aws-sdk+client-rds-data@3.319.0_kysely@0.23.5_mysql2@2.3.3/node_modules/src/mysql2/session.ts:79:18)
at execute (/workspaces/amni-sst/node_modules/.pnpm/drizzle-orm@0.25.3_@aws-sdk+client-rds-data@3.319.0_kysely@0.23.5_mysql2@2.3.3/node_modules/src/mysql-core/session.ts:66:5)
at execute (/workspaces/amni-sst/node_modules/.pnpm/drizzle-orm@0.25.3_@aws-sdk+client-rds-data@3.319.0_kysely@0.23.5_mysql2@2.3.3/node_modules/src/mysql-core/db.ts:89:23)
at async (/workspaces/amni-sst/node_modules/.pnpm/drizzle-orm@0.25.3_@aws-sdk+client-rds-data@3.319.0_kysely@0.23.5_mysql2@2.3.3/node_modules/src/mysql-core/dialect.ts:53:16)
at async (/workspaces/amni-sst/node_modules/.pnpm/drizzle-orm@0.25.3_@aws-sdk+client-rds-data@3.319.0_kysely@0.23.5_mysql2@2.3.3/node_modules/src/mysql2/session.ts:200:25)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async (/workspaces/amni-sst/node_modules/.pnpm/drizzle-orm@0.25.3_@aws-sdk+client-rds-data@3.319.0_kysely@0.23.5_mysql2@2.3.3/node_modules/src/mysql-core/dialect.ts:44:40)
at async (/workspaces/amni-sst/node_modules/.pnpm/drizzle-orm@0.25.3_@aws-sdk+client-rds-data@3.319.0_kysely@0.23.5_mysql2@2.3.3/node_modules/src/mysql2/migrator.ts:6:40)
at <anonymous> (/workspaces/amni-sst/packages/functions/src/migrator.ts:9:3)
```

Generated SQL file (one of many that fired the same issue) ::

```
CREATE TABLE `another_table` (
	`id` int AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`url` text
);

CREATE TABLE `joiner_table` (
	`id` serial AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`rds_proxy_test_table_id` int,
	`another_table` int
);

CREATE TABLE `rds_proxy` (
	`id` int AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`url` text
);

ALTER TABLE `joiner_table` ADD CONSTRAINT `joiner_table_rds_proxy_test_table_id_rds_proxy_id_fk` FOREIGN KEY (`rds_proxy_test_table_id`) REFERENCES `rds_proxy`(`id`);
ALTER TABLE `joiner_table` ADD CONSTRAINT `joiner_table_another_table_another_table_id_fk` FOREIGN KEY (`another_table`) REFERENCES `another_table`(`id`);
```

Drizzle Schema :: 

```
import { int, mysqlTable, serial, text } from 'drizzle-orm/mysql-core';

export const rdsProxyTestTable = mysqlTable('rds_proxy', {
  id: int('id').autoincrement().primaryKey(),
  url: text('url'),
});

export const anotherTable = mysqlTable('another_table', {
  id: int('id').autoincrement().primaryKey(),
  url: text('url'),
});

export const joinerTable = mysqlTable('joiner_table', {
  id: serial('id').primaryKey(),
  rdsProxyTestTableId: int('rds_proxy_test_table_id').references(
    () => rdsProxyTestTable.id,
  ),
  anotherTableId: int('another_table').references(() => anotherTable.id),
});


```

The SQL, exactly as it is, runs fine in DBA Tool (DBeaver, in my case).

In initial renditions of the same problem, 
I was on dumb 'ol windows. 

So I thought, perhaps, there was some windows-specific issue (e.g., EoL formatting) messing with whatever parses the SQL as/before the migrator has it executed by the mysql instance.

Codeblocks above are from a codespace, exhibiting the same behavior::

1. Take an arbitrary (?) // incomplete chunk of SQL
2. Try to run it
3. It errors, missing its full context

**Comment by AndriiSherman** [comment]
You need to enable breakpoints and regenerate the migration 

https://github.com/drizzle-team/drizzle-kit-mirror#configuration

and then run it 1 more time

**Comment by NicholasFields** [comment]
Kk, brilliant.

My B 
& thanks!

**Comment by NicholasFields** [comment]
For anyone who might need more [mysql] enrichment, as I did.

Mysql doesn't support transactions for DDL execution, whereas Postgres does.

Google shall suffice from there.

Cheers 🤗
