### ISSUE TITLE
Error on drizzle-kit push, Cannot read properties of undefined (reading 'type') 

### ISSUE THREAD

**Issue by FranCanias** [drizzle-team/drizzle-kit-mirror#431]
Hi! i have this error when i do 'npx drizzle-kit push', i fixed it adding a question mark on 'node_modules/drizzle-kit/bin.cjs:111813:123' 

this is the following error im getting in the terminal: 

`npx drizzle-kit push               
drizzle-kit: v0.21.4
drizzle-orm: v0.30.10

No config path provided, using default path
Reading config file '/Users/x/x/x/drizzle.config.ts'
[✓] Pulling schema from database...Reading schema files:
/Users/x/x/x/src/server/schema.ts

TypeError: Cannot read properties of undefined (reading 'type')
    at /Users/x/x/x/node_modules/drizzle-kit/bin.cjs:111813:123
    at Array.filter (<anonymous>)
    at filterStatements (/Users/x/x/x/node_modules/drizzle-kit/bin.cjs:111793:25)
    at mysqlPush (/Users/x/x/x/node_modules/drizzle-kit/bin.cjs:114380:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (/Users/x/x/x/node_modules/drizzle-kit/bin.cjs:121465:7)`

npx: 10.2.4
node: v20.11.0

the line i modified to fix it is the following: 
`if (unsquashed.columns.length === 1 && currentSchema.tables[statement.tableName].columns[unsquashed.columns[0]]**?**.type === "serial" && prevSchema.tables[statement.tableName].columns[unsquashed.columns[0]].type === "serial" && currentSchema.tables[statement.tableName].columns[unsquashed.columns[0]].name === unsquashed.columns[0]) {`

**Comment by PurpleTape** [comment]
Also faced with it

```
> drizzle-kit push

drizzle-kit: v0.21.4
drizzle-orm: v0.30.10

No config path provided, using default path
Reading config file '/my-app-path/drizzle.config.ts'
Using 'pg' driver for database querying
[✓] Pulling schema from database...TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at /my-app-path/node_modules/drizzle-kit/bin.cjs:18362:23
    at Array.map (<anonymous>)
    at alternationsInColumn (/my-app-path/node_modules/drizzle-kit/bin.cjs:18361:10)
    at /my-app-path/node_modules/drizzle-kit/bin.cjs:18321:49
    at Array.map (<anonymous>)
    at findAlternationsInTable (/my-app-path/node_modules/drizzle-kit/bin.cjs:18321:37)
    at /my-app-path/node_modules/drizzle-kit/bin.cjs:18203:14
    at Array.map (<anonymous>)
    at applyJsonDiff (/my-app-path/node_modules/drizzle-kit/bin.cjs:18201:69)
    at applyPgSnapshotsDiff (/my-app-path/node_modules/drizzle-kit/bin.cjs:19822:26)

```

**Comment by AlexBlokh** [comment]
please provide database/typescript drizzle schema

**Comment by PurpleTape** [comment]
@AlexBlokh 

Hello!

In my case, the error occurs during the following action:

1. The database is empty, the table does not exist
```
> drizzle-kit push
```

2. The table was created without errors, run the command again
```
> drizzle-kit push

drizzle-kit: v0.21.4
drizzle-orm: v0.30.10

No config path provided, using default path
Reading config file '/app/drizzle.config.ts'
Using 'pg' driver for database querying
[✓] Pulling schema from database...TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at /app/node_modules/drizzle-kit/bin.cjs:18362:23
    at Array.map (<anonymous>)
    at alternationsInColumn (/app/node_modules/drizzle-kit/bin.cjs:18361:10)
    at /app/node_modules/drizzle-kit/bin.cjs:18321:49
    at Array.map (<anonymous>)
    at findAlternationsInTable (/app/node_modules/drizzle-kit/bin.cjs:18321:37)
    at /app/node_modules/drizzle-kit/bin.cjs:18203:14
    at Array.map (<anonymous>)
    at applyJsonDiff (/app/node_modules/drizzle-kit/bin.cjs:18201:69)
    at applyPgSnapshotsDiff (/app/node_modules/drizzle-kit/bin.cjs:19822:26)
```

My scheme:
```ts
import { pgTable, serial, timestamp } from 'drizzle-orm/pg-core';

export const test = pgTable('test', {
    id: serial('id').primaryKey().notNull(),
    deactivatedDate: timestamp('deactivated_date', {
        mode: 'date',
        precision: 0,
    }),
});
```

Config:
```ts
import { defineConfig } from 'drizzle-kit';

export default defineConfig({
    dialect: 'postgresql',
    out: './migrations',
    schema: [
        './drizzle-test/*.schema.ts',
    ],
    dbCredentials: {
        host: 'localhost',
        port: 5432,
        user: 'user',
        password: 'password',
        database: 'drizzle-test',
    },
    verbose: true,
    strict: true,
});
```

**Comment by PurpleTape** [comment]
Also, when I remove the `deactivated_date` column, there is no error when running the command

**Comment by dankgarlic1** [comment]
> Also, when I remove the `deactivated_date` column, there is no error when running the command

I am also facing the same issue, the problem is with timestamp, any solutions?
