### ISSUE TITLE
Drizzle Studio: Error: Connection terminated unexpectedly

### ISSUE THREAD

**Issue by johnforte** [drizzle-team/drizzle-kit-mirror#435]
```
Drizzle Studio is up and running on https://local.drizzle.studio
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Connection terminated unexpectedly
    at Connection3.<anonymous> (node_modules/drizzle-kit/bin.cjs:62051:78)
    at Object.onceWrapper (node:events:627:28)
    at Connection3.emit (node:events:513:28)
    at Socket.<anonymous> (node_modules/drizzle-kit/bin.cjs:61519:17)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:757:14)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Emitted 'error' event on Client2 instance at:
    at Client2._handleErrorEvent (node_modules/drizzle-kit/bin.cjs:62228:14)
    at Connection3.<anonymous> (node_modules/drizzle-kit/bin.cjs:62063:20)
    at Object.onceWrapper (node:events:627:28)
    [... lines matching original stack trace ...]
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)

```
Happens when I don't interact with the db studio for a while, seems it needs some keep alive packet to be sent.

I am using neon.tech.
drizzle-kit: v0.21.1
drizzle-orm: v0.30.10

**Comment by AndriiSherman** [comment]
fixed in `drizzle-kit@0.22.0`
