### ISSUE TITLE
dbCredentials.ssl flag does not work.

### ISSUE THREAD

**Issue by Ymirke** [drizzle-team/drizzle-kit-mirror#436]
Adding "ssl: true" does not work for the defineConfig argument.

## Does not work:
```ts
import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "postgresql",
  schema: "./src/db/*",
  out: "./migrations",
  verbose: true,
  dbCredentials: {
    url: "<psql-connect-string>",
    ssl: true,
  },
});
```
### Error recieved:
```
> next@0.1.0 migrate <project-path>
> drizzle-kit migrate

drizzle-kit: v0.21.4
drizzle-orm: v0.30.10

No config path provided, using default path
Reading config file '<project-path>/drizzle.config.ts'
Using 'postgres' driver for database querying
[⣷] applying migrations...PostgresError: SSL/TLS required
    at ErrorResponse (/<project-path>/node_modules/.pnpm/drizzle-kit@0.21.4/node_modules/drizzle-kit/bin.cjs:71410:27)
    at handle (/<project-path>/node_modules/.pnpm/drizzle-kit@0.21.4/node_modules/drizzle-kit/bin.cjs:71187:7)
    at Socket.data (/<project-path>/node_modules/.pnpm/drizzle-kit@0.21.4/node_modules/drizzle-kit/bin.cjs:71010:9)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  severity_local: 'FATAL',
  code: '28000'
}
```

## Works:
```ts
import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "postgresql",
  schema: "./src/db/*",
  out: "./migrations",
  verbose: true,
  dbCredentials: {
    url: "<psql-connect-string>?ssl=true",
  },
});
```

**Comment by AlexBlokh** [comment]
it's either `url` or a set of params with `ssl`, due to https://orm.drizzle.team/kit-docs/config-reference#dbcredentials
