### ISSUE TITLE
Drizzle Database showing problem after run the drizzle 

### ISSUE THREAD

**Issue by Tarunroy20** [drizzle-team/drizzle-kit-mirror#445]
may data base is not showing after giving the command , "npx drizzle-kit studio" in Terminal

**Comment by drapalad** [comment]
Hello, I guess I'm facing same issue while using studio
```
Error: self-signed certificate
    at D:\projects\private\gielda\backend\node_modules\drizzle-kit\bin.cjs:77692:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async proxy (D:\projects\private\gielda\backend\node_modules\drizzle-kit\bin.cjs:119635:26)
    at async D:\projects\private\gielda\backend\node_modules\drizzle-kit\bin.cjs:128205:26
    at async dispatch (D:\projects\private\gielda\backend\node_modules\drizzle-kit\bin.cjs:125794:21)
    at async D:\projects\private\gielda\backend\node_modules\drizzle-kit\bin.cjs:125454:9
    at async dispatch (D:\projects\private\gielda\backend\node_modules\drizzle-kit\bin.cjs:125794:21)
    at async D:\projects\private\gielda\backend\node_modules\drizzle-kit\bin.cjs:128158:9
    at async dispatch (D:\projects\private\gielda\backend\node_modules\drizzle-kit\bin.cjs:125794:21)
    at async cors2 (D:\projects\private\gielda\backend\node_modules\drizzle-kit\bin.cjs:126962:9) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
```
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/89295677/198d9c08-2d8d-4480-a7e3-1692826de596)

I'm accessing it through `https://local.drizzle.studio/`, and everything is running on my local machine (win11).

It worked in version: [0.20.17](https://npmjs.com/package/drizzle-kit)
I've updated to [0.22.0](https://npmjs.com/package/drizzle-kit) where it broke, and then to [0.22.1](https://npmjs.com/package/drizzle-kit), but still facing same issue.
I haven't tested any version in between, but if it will be any use I can do so.

**Comment by akdmi** [comment]
I am facing the same issue as well. Running 0.22.1 as well. Any update on this?
<img width="301" alt="image" src="https://github.com/drizzle-team/drizzle-kit-mirror/assets/170224400/f5ab42ec-0cfc-4360-988b-16e2121f67c2">
