### ISSUE TITLE
CLI generate migrations fails with ts module resolution "nodenext"

### ISSUE THREAD

**Issue by mandarzope** [drizzle-team/drizzle-kit-mirror#462]
While running migrations in following setup "drizzle-kit": "^0.22.7" throws error with typescript and type:module setup
```
// tsconfig.json
    "module": "nodenext",
    "moduleResolution": "nodenext",

// src/auth/schema/auth.models.ts - drizzle schema files 
import { users } from '../../core/schema/core.models.js'
```
```
// Error
Error: Cannot find module '../../core/schema/core.models.js'
Require stack:
- /Users/unknown/work/src/auth/schema/auth.models.ts
- /Users/unknown/work/node_modules/.pnpm/drizzle-kit@0.22.7/node_modules/drizzle-kit/bin.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Module._resolveFilename (/Users/unknown/work/node_modules/.pnpm/drizzle-kit@0.22.7/node_modules/drizzle-kit/bin.cjs:19969:40)
    at Module._load (node:internal/modules/cjs/loader:1038:27)
    at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
    at Module.require (node:internal/modules/cjs/loader:1297:12)
    at require (node:internal/modules/helpers:123:16)
    at Object.<anonymous> (/Users/unknown/work/src/auth/schema/auth.models.ts:2:23)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Module._compile (/Users/unknown/work/node_modules/.pnpm/drizzle-kit@0.22.7/node_modules/drizzle-kit/bin.cjs:17466:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1544:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/unknown/work/src/auth/schema/auth.models.ts',
    '/Users/unknown/work/node_modules/.pnpm/drizzle-kit@0.22.7/node_modules/drizzle-kit/bin.cjs'
  ]
}
```

Currently this is fixed by modifying drizzle-kit/bin.cjs
```
      Module._resolveFilename = function(request, _parent) {
        const isCoreModule = _module2.builtinModules.includes(request);
        if (!isCoreModule) {
          const found = matchPath(request);
          if (found) {
            const modifiedArguments = [found, ...[].slice.call(arguments, 1)];
            return originalResolveFilename.apply(this, modifiedArguments);
          }
        }
       /***********************Temporary fix start***************************/

      if (request.endsWith('.js')) {
        const found = path.resolve(_parent.path, request.replace('.js', '.ts'))
        if (fs.existsSync(found)) {
          const modifiedArguments = [found, ...[].slice.call(arguments, 1)];
          return originalResolveFilename.apply(this, modifiedArguments);
        }
      }
       /***********************Temporary fix end***************************/
        return originalResolveFilename.apply(this, arguments);
      };
      return () => {
        Module._resolveFilename = originalResolveFilename;
      };
    }
```

**Comment by shrinktofit** [comment]
+1. Also failed with "Node16".

**Comment by RogutKuba** [comment]
still getting this...

**Comment by Shyrogan** [comment]
This is a patch that works with Svelte 5, note that package managers such as `bun` and `pnpm` offer patching generally through the `bun patch` commad:
```patch
diff --git a/bin.cjs b/bin.cjs
index 96235f52f7d0fcaed6abb588107a9fed948bd808..95d4eabc57367e599ceef4185c5e2fa7cedb4e0c 100755
--- a/bin.cjs
+++ b/bin.cjs
@@ -17138,6 +17138,16 @@ var require_node2 = __commonJS({
             return originalResolveFilename.apply(this, modifiedArguments);
           }
         }
+       /***********************Temporary fix start***************************/
+
+      if (request.endsWith('.js')) {
+        const found = require('path').resolve(_parent.path, request.replace('.js', '.ts'))
+        if (require('fs').existsSync(found)) {
+          const modifiedArguments = [found, ...[].slice.call(arguments, 1)];
+          return originalResolveFilename.apply(this, modifiedArguments);
+        }
+      }
+       /***********************Temporary fix end***************************/
         return originalResolveFilename.apply(this, arguments);
       };
       return () => {
```

This is not an ideal solution but "it just works"

**Comment by misium** [comment]
Appreciate the report @mandarzope. Same issue here.

drizzle-kit: 0.24.2.

The above fix didn't work for me (and I'd like to avoid patching libraries that I'll only break again when upgrading / re-installing).

Instead I pointed drizzle.config.ts to the _compiled_ schema.js file instead of the uncompiled schema.ts file. In my case:

```
// tsconfig.json
"compilerOptions": {
  "rootDir": "src",
  "outDir": "dist",
  ...
}
```
and then
```
// OLD drizzle.config.ts
export default defineConfig({
  ...
  schema: "./src/db/schema.ts",
  ...
})
```

```
// NEW, FIXED drizzle.config.ts
export default defineConfig({
  ...
  schema: "./dist/db/schema.js",
  ...
})
```

Not a great fix! Requires compiling before running drizzle-kit generate/migrate. But still a one-liner if you tweak your package.json to run tsc before drizzle-kit generate/migrate (see [npm docs on pre/post scripts](https://docs.npmjs.com/cli/v10/using-npm/scripts)):

```
// package.json
"scripts": {
  ...
  "pregenerate-sql": "tsc",
  "generate-sql": "drizzle-kit generate",
  "premigrate-sql": "tsc",
  "migrate-sql": "drizzle-kit migrate"
  ...
}
```

FWIW: drizzle-kit generate/migrate _were_ working exactly as expected until now. No idea what changed -- the only recent change to my tsconfig.json was adding `skipLibCheck: true` (and alas, that flag was only turned on because of the ts compile errors thrown by drizzle-orm).

But take that with a grain of salt: doesn't make sense that `skipLibCheck` would break this, and reverting it to `false` didn't fix either. But it's the only hint I could glean from our commit history.

**Comment by 58bits** [comment]
Also the same issue here with `"skipLibCheck": true,` to disable Drizzle ORM warnings, and `"moduleResolution": "NodeNext",` 

We're using @misium  's suggested workaround with the following package.json 

```json
"scripts": {
  "clean": "rm -rf node_modules build dist .turbo",
  "build": "tsc -p tsconfig.json",
  "start": "node dist/index.js",
  "test": "tsx --test $(find . -name \"*.test.ts\")",
  "dev": "tsx --no-warnings --env-file=.env --watch ./index.ts | pino-pretty --colorize",
  "drizzle:generate": "tsc -p tsconfig.json && drizzle-kit generate --config=drizzle.config.ts",
  "drizzle:migrate": "drizzle-kit migrate --config=drizzle.config.ts",
  "drizzle:seed": "tsx --no-warnings --env-file=.env ./database/drizzle/seeds/index.ts"
},
```

And our `drizzle.config.ts` as....

```ts
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: 'postgresql',
  schema: './dist/database/drizzle/schema/index.js',
  out: './database/drizzle/migrations',
  dbCredentials: {
    url: process.env.POSTGRES_CONNECTION_STRING as string,
  },
  verbose: true,
  strict: true,
})
```

For completeness, here's our `tsconfig.json` file....

```json
{
  "compilerOptions": {
    "lib": ["es2020"],
    "module": "NodeNext",
    "target": "es2020",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "incremental": true,
    "noImplicitAny": false,
    "moduleResolution": "NodeNext",
    "sourceMap": true,
    "outDir": "./dist",
    "skipLibCheck": true,
    "baseUrl": "./",
    "paths": {
      "config/*": ["config/*"],
      "@/*": ["./src/*"]
    },
    "types": ["node"]
  },
  "include": ["index.ts", "fastify.d.ts", "config", "src", "test"],
  "exclude": ["node_modules", "dist", "coverage"]
}
```
