### ISSUE TITLE
error: enum label "xxxxx" already exists

### ISSUE THREAD

**Issue by JohnCido** [drizzle-team/drizzle-kit-mirror#464]
Just updated my `drizzle-kit` from `^0.20.10-8c690cf` to `^0.22.7`. And I've performed all requested [migrations](https://orm.drizzle.team/kit-docs/upgrade-21).

Without making any changes to the schemas, the `drizzle-kit push` simply fails with following output:

```log
drizzle-kit: v0.22.7
drizzle-orm: v0.31.2

Custom config path was provided, using 'drizzle.config.ts'
Reading config file '/Users/***********/drizzle.config.ts'
Using 'pg' driver for database querying
[✓] Pulling schema from database...
error: enum label "xxxxx" already exists
    at /Users/***********/node_modules/drizzle-kit/bin.cjs:77696:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.query (/Users/***********/node_modules/drizzle-kit/bin.cjs:119635:26)
    at async pgPush (/Users/***********/node_modules/drizzle-kit/bin.cjs:122560:13)
    at async _Command.<anonymous> (/Users/***********/node_modules/drizzle-kit/bin.cjs:129681:7) {
  length: 92,
  severity: 'ERROR',
  code: '42710',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'pg_enum.c',
  line: '267',
  routine: 'AddEnumLabel'
}
```

It just complains about existing enum labels I've created before. This never happened to me before the upgrade. I've also tried the latest version of `pg`, no luck.

**Comment by kravetsone** [comment]
+1

**Comment by MickL** [comment]
In Drizzle repo the same issue has 20 Upvotes: https://github.com/drizzle-team/drizzle-orm/issues/2389

**Comment by Ricardosgeral** [comment]
I have the same issue
