### ISSUE TITLE
Composite pk always causes drizzle-kit push to crash.

### ISSUE THREAD

**Issue by thebjorn** [drizzle-team/drizzle-kit-mirror#472]
The following table (from Auth.js)
```
export const authenticators = pgTable(
  "authenticator",
  {
    credentialID: text("credentialID").notNull().unique(),
    userId: text("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    providerAccountId: text("providerAccountId").notNull(),
    credentialPublicKey: text("credentialPublicKey").notNull(),
    counter: integer("counter").notNull(),
    credentialDeviceType: text("credentialDeviceType").notNull(),
    credentialBackedUp: boolean("credentialBackedUp").notNull(),
    transports: text("transports"),
  },
(table) => {
	return {
        pk: primaryKey({
            name: 'authenticator_userid_credentialid_pk',
            columns: [table.userId, table.credentialID],
        })
	}
}
);
```
Always causes `drizzle-kit push` to crash with the following error:
```
srv/lib/../../db❱ pnpm drizzle-kit push                                                                                                                                                                         
drizzle-kit: v0.22.7
drizzle-orm: v0.31.2

No config path provided, using default path
Reading config file 'C:\srv\lib\tilly\packages\db\drizzle.config.ts'
Using 'pg' driver for database querying
[✓] Pulling schema from database...

 Warning  You are about to execute current statements:

ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_userid_credentialid_pk";

ALTER TABLE "Topic" ALTER COLUMN "number" SET DEFAULT '1';
DO $$ BEGIN
 ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

ALTER TABLE "authenticator" DROP CONSTRAINT authenticator_userId_credentialID_pk;
--> statement-breakpoint
ALTER TABLE "authenticator" ADD CONSTRAINT authenticator_userId_credentialID_pk PRIMARY KEY(userId,credentialID);

error: constraint "authenticator_userid_credentialid_pk" of relation "authenticator" does not exist
    at C:\srv\lib\tilly\node_modules\.pnpm\drizzle-kit@0.22.7\node_modules\drizzle-kit\bin.cjs:77696:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.query (C:\srv\lib\tilly\node_modules\.pnpm\drizzle-kit@0.22.7\node_modules\drizzle-kit\bin.cjs:119635:26)
    at async pgPush (C:\srv\lib\tilly\node_modules\.pnpm\drizzle-kit@0.22.7\node_modules\drizzle-kit\bin.cjs:122560:13)
    at async _Command.<anonymous> (C:\srv\lib\tilly\node_modules\.pnpm\drizzle-kit@0.22.7\node_modules\drizzle-kit\bin.cjs:129681:7) {
  length: 162,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '12070',
  routine: 'ATExecDropConstraint'
}
```
Running the drop constraint command manually works (and afterwards the `drizzle-kit push` command works again - which is quite the hazzle):
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/1193143/d937525a-3cbc-4a73-a0cc-aeda5cf35769)

**Comment by ronnyandre** [comment]
This should really be fixed, but thanks for the temporary solution!

**Comment by falkmatt91** [comment]
Having the same issue as well.

**Comment by macklinhrw** [comment]
same issue

**Comment by BahaaZidan** [comment]
Same issue here. The suggested workaround doesn't work for me. So I dropped all tables and tried `drizzle-kit generate` then `drizzle-kit migrate`. That worked 👍

**Comment by romi6** [comment]
Same issue here. The suggested workaround didn't work for me. It only works when I drop all tables and generate again. Anybody got a different solution then having to drop tables? xD

**Comment by shaunchurch** [comment]
Also seeing this issue with the Auth.js `authenticator` table composite primary key in Postgres. Seems to happen with any migration _after_ running the migration that sets up the auth.js tables.

If you generate new migrations after adding the authenticator table, then comment out the composite key in the schema, you can run the new migration still without dropping any tables, but I'm not sure if there are any issues that come from doing this...

**Comment by shaunchurch** [comment]
For anyone else running to this, a colleague figured out it's because of the casing for the columns in the authenticator schema. Rename the defaults to remove the case. The migration looks like this: 

```sql
ALTER TABLE "authenticator" RENAME COLUMN "credentialID" TO "credential_id";--> statement-breakpoint
ALTER TABLE "authenticator" RENAME COLUMN "userId" TO "user_id";--> statement-breakpoint
ALTER TABLE "authenticator" RENAME COLUMN "providerAccountId" TO "provider_account_id";--> statement-breakpoint
ALTER TABLE "authenticator" RENAME COLUMN "credentialPublicKey" TO "credential_public_key";--> statement-breakpoint
ALTER TABLE "authenticator" RENAME COLUMN "credentialDeviceType" TO "credential_device_type";--> statement-breakpoint
ALTER TABLE "authenticator" RENAME COLUMN "credentialBackedUp" TO "credential_backed_up";--> statement-breakpoint
ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_credentialID_unique";--> statement-breakpoint
ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_userId_user_id_fk";
--> statement-breakpoint
ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_userId_credentialID_pk";--> statement-breakpoint
ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_user_id_credential_id_pk" PRIMARY KEY("user_id","credential_id");--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_credential_id_unique" UNIQUE("credential_id");
```

**Comment by VictorLandim** [comment]
We need a solution for this. I'm facing the same issue.

**Comment by AliMejbar** [comment]
Same issue here, definitly needs a fix !

**Comment by NicHaley** [comment]
Running into this too

**Comment by sjbigger** [comment]
> For anyone else running to this, a colleague figured out it's because of the casing for the columns in the authenticator schema. Rename the defaults to remove the case. The migration looks like this:
> 
> ```sql
> ALTER TABLE "authenticator" RENAME COLUMN "credentialID" TO "credential_id";--> statement-breakpoint
> ALTER TABLE "authenticator" RENAME COLUMN "userId" TO "user_id";--> statement-breakpoint
> ALTER TABLE "authenticator" RENAME COLUMN "providerAccountId" TO "provider_account_id";--> statement-breakpoint
> ALTER TABLE "authenticator" RENAME COLUMN "credentialPublicKey" TO "credential_public_key";--> statement-breakpoint
> ALTER TABLE "authenticator" RENAME COLUMN "credentialDeviceType" TO "credential_device_type";--> statement-breakpoint
> ALTER TABLE "authenticator" RENAME COLUMN "credentialBackedUp" TO "credential_backed_up";--> statement-breakpoint
> ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_credentialID_unique";--> statement-breakpoint
> ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_userId_user_id_fk";
> --> statement-breakpoint
> ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_userId_credentialID_pk";--> statement-breakpoint
> ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_user_id_credential_id_pk" PRIMARY KEY("user_id","credential_id");--> statement-breakpoint
> DO $$ BEGIN
>  ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
> EXCEPTION
>  WHEN duplicate_object THEN null;
> END $$;
> --> statement-breakpoint
> ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_credential_id_unique" UNIQUE("credential_id");
> ```

This worked for me. Manually rename all columns to snake case and then push the changes.

**Comment by macklinhrw** [comment]
> > For anyone else running to this, a colleague figured out it's because of the casing for the columns in the authenticator schema. Rename the defaults to remove the case. The migration looks like this:
> > ```sql
> > ALTER TABLE "authenticator" RENAME COLUMN "credentialID" TO "credential_id";--> statement-breakpoint
> > ALTER TABLE "authenticator" RENAME COLUMN "userId" TO "user_id";--> statement-breakpoint
> > ALTER TABLE "authenticator" RENAME COLUMN "providerAccountId" TO "provider_account_id";--> statement-breakpoint
> > ALTER TABLE "authenticator" RENAME COLUMN "credentialPublicKey" TO "credential_public_key";--> statement-breakpoint
> > ALTER TABLE "authenticator" RENAME COLUMN "credentialDeviceType" TO "credential_device_type";--> statement-breakpoint
> > ALTER TABLE "authenticator" RENAME COLUMN "credentialBackedUp" TO "credential_backed_up";--> statement-breakpoint
> > ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_credentialID_unique";--> statement-breakpoint
> > ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_userId_user_id_fk";
> > --> statement-breakpoint
> > ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_userId_credentialID_pk";--> statement-breakpoint
> > ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_user_id_credential_id_pk" PRIMARY KEY("user_id","credential_id");--> statement-breakpoint
> > DO $$ BEGIN
> >  ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
> > EXCEPTION
> >  WHEN duplicate_object THEN null;
> > END $$;
> > --> statement-breakpoint
> > ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_credential_id_unique" UNIQUE("credential_id");
> > ```
> 
> This worked for me. Manually rename all columns to snake case and then push the changes.

This also seems to have worked for me. I also had to change the column names in the schema after doing the migration.

**Comment by BCusack** [comment]
> > > For anyone else running to this, a colleague figured out it's because of the casing for the columns in the authenticator schema. Rename the defaults to remove the case. The migration looks like this:
> > > ```sql
> > > ALTER TABLE "authenticator" RENAME COLUMN "credentialID" TO "credential_id";--> statement-breakpoint
> > > ALTER TABLE "authenticator" RENAME COLUMN "userId" TO "user_id";--> statement-breakpoint
> > > ALTER TABLE "authenticator" RENAME COLUMN "providerAccountId" TO "provider_account_id";--> statement-breakpoint
> > > ALTER TABLE "authenticator" RENAME COLUMN "credentialPublicKey" TO "credential_public_key";--> statement-breakpoint
> > > ALTER TABLE "authenticator" RENAME COLUMN "credentialDeviceType" TO "credential_device_type";--> statement-breakpoint
> > > ALTER TABLE "authenticator" RENAME COLUMN "credentialBackedUp" TO "credential_backed_up";--> statement-breakpoint
> > > ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_credentialID_unique";--> statement-breakpoint
> > > ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_userId_user_id_fk";
> > > --> statement-breakpoint
> > > ALTER TABLE "authenticator" DROP CONSTRAINT "authenticator_userId_credentialID_pk";--> statement-breakpoint
> > > ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_user_id_credential_id_pk" PRIMARY KEY("user_id","credential_id");--> statement-breakpoint
> > > DO $$ BEGIN
> > >  ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
> > > EXCEPTION
> > >  WHEN duplicate_object THEN null;
> > > END $$;
> > > --> statement-breakpoint
> > > ALTER TABLE "authenticator" ADD CONSTRAINT "authenticator_credential_id_unique" UNIQUE("credential_id");
> > > ```
> > 
> > 
> > This worked for me. Manually rename all columns to snake case and then push the changes.
> 
> This also seems to have worked for me. I also had to change the column names in the schema after doing the migration.

I originally went with this solution but found using the Google provider still had issues with userId as user_id failing -> As I'm not implementing authenticators in my application I just removed the composite primary key from the authenticator table

**Comment by amaringonz** [comment]
The issue with composite primary keys in the `authenticator` table can be resolved with a simple workaround. Renaming the primary key constraint to use consistent lowercase formatting should allow the migration to proceed without crashes. Please use the following SQL command:

```sql
ALTER TABLE "authenticator" 
RENAME CONSTRAINT "authenticator_userId_credentialId_pk" 
TO "authenticator_userid_credentialid_pk";
