### ISSUE TITLE
Can't apply migrations after upgrade from 0.20.14 to 0.22.7

### ISSUE THREAD

**Issue by StarpTech** [drizzle-team/drizzle-kit-mirror#482]
Hi, we have followed the migration guides here https://orm.drizzle.team/kit-docs/upgrade-21#how-to-migrate-to-0210 but after running our migration script again we get an error.

Before drizzle-kit 0.21.0 it was not possible to use the new `migrate` command. For this reason, we used the `drizzle-orm/postgres-js/migrator` package to run migrations. Now, it seems this is no longer compatible with the latest version.

Migration script:

```ts
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { buildDatabaseConnectionConfig, DatabaseConnectionConfig } from './plugins/database.js';

export async function RunMigration(databaseConnectionUrl: string, opts?: DatabaseConnectionConfig) {
  const connectionConfig = await buildDatabaseConnectionConfig(opts);
  const migrationConnection = postgres(databaseConnectionUrl, {
    ...connectionConfig,
    onnotice: (_) => {},
    max: 1,
  });

  await migrate(drizzle(migrationConnection), {
    migrationsFolder: 'migrations',
    migrationsTable: 'migrations',
  });

  await migrationConnection.end({
    timeout: 5,
  });
}
```

This is error is from the first migration file and it was already applied. After upgrading, drizzle-kit forgot what migrations has been already applied.

```
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^

PostgresError: column "schema_version_id" referenced in foreign key constraint does not exist
    at ErrorResponse (file:///Users/starptech/p/wundergraph/cosmo/node_modules/.pnpm/postgres@3.4.3/node_modules/postgres/src/connection.js:790:26)
    at handle (file:///Users/starptech/p/wundergraph/cosmo/node_modules/.pnpm/postgres@3.4.3/node_modules/postgres/src/connection.js:476:6)
    at Socket.data (file:///Users/starptech/p/wundergraph/cosmo/node_modules/.pnpm/postgres@3.4.3/node_modules/postgres/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42703',
  where: 'SQL statement "ALTER TABLE "federated_graphs" ADD CONSTRAINT "federated_graphs_schema_version_id_schema_versions_id_fk" FOREIGN KEY ("schema_version_id") REFERENCES "schema_versions"("id") ON DELETE cascade ON UPDATE no action"\n' +
    'PL/pgSQL function inline_code_block line 2 at SQL statement',
  file: 'tablecmds.c',
  line: '11285',
  routine: 'transformColumnNameList'
}
```

**Comment by StarpTech** [comment]
Thanks again @AndriiSherman for your help. The resolution is to set the correct migrationsTable value.

```diff
  await migrate(drizzle(migrationConnection), {
    migrationsFolder: 'migrations',
-- migrationsTable: 'migrations',
  });
```
We initially migrated with the defaults. After that this was ignored in previous versions but produce conflicts in the latest version.
