### ISSUE TITLE
[BUG]: Cannot push to a Turso schema database with @libsql/client version greater than 0.6.0

### ISSUE THREAD

**Issue by crbanman** [drizzle-team/drizzle-kit-mirror#484]
### What version of drizzle-orm are you using?
0.31.2

### What version of drizzle-kit are you using?
0.22.8

### Describe the Bug
1. Have installed any version of `@libsql/client` greater than 0.6.0
2. Create a "schema" database on Turso
   - `turso db create schema-database --type schema`
3. Attempt to use `drizzle-kit push` to the schema database

Upon completing step 3 I receive an error:

```text
❯ pnpm drizzle-kit push --config <my drizzle config>.ts       
drizzle-kit: v0.22.8
drizzle-orm: v0.31.2

Custom config path was provided, using '<my drizzle config>.ts'
Reading config file '<path to my drizzle config>'
[⣷] Pulling schema from database...
Error: No migrations found
    at getLastMigrationJob (file:///<path to my applications depenencies>/node_modules/.pnpm/@libsql+client@0.7.0/node_modules/@libsql/client/lib-esm/migrations.js:79:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async waitForLastMigrationJobToFinish (file:///<path to my applications depenencies>/node_modules/.pnpm/@libsql+client@0.7.0/node_modules/@libsql/client/lib-esm/migrations.js:97:30)
    at async file:///<path to my applications depenencies>/node_modules/.pnpm/@libsql+client@0.7.0/node_modules/@libsql/client/lib-esm/http.js:79:21
    at async Object.query (<path to my applications depenencies>/node_modules/.pnpm/drizzle-kit@0.22.8/node_modules/drizzle-kit/bin.cjs:119857:27)
    at async fromDatabase3 (<path to my applications depenencies>/node_modules/.pnpm/drizzle-kit@0.22.8/node_modules/drizzle-kit/bin.cjs:22311:23)
```

I've tested and it works fine with `@libsql/client@0.6.0`.

I do not know if this is an issue with drizzle or if it's an issue with `@libsql/client`.

I suspect this commit (https://github.com/tursodatabase/libsql-client-ts/pull/206) which was added in `@libsql/client@0.6.1` is responsible for issue, though I have not done further digging/testing.

**Comment by j13n** [comment]
I'm getting the same behaviour. Tried 0.6.2, upgraded to 0.7.0 without any results. Downgraded to 0.6.0 and I can push to database schema.

`> drizzle-kit push --config=./drizzle/drizzle.config-orgs.ts

drizzle-kit: v0.22.8
drizzle-orm: v0.31.2

Custom config path was provided, using './drizzle/drizzle.config-orgs.ts'
Reading config file '<path>/drizzle/drizzle.config-orgs.ts'
[⣯] Pulling schema from database...
Error: No migrations found
    at getLastMigrationJob (file://<path>/node_modules/@libsql/client/lib-esm/migrations.js:79:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async waitForLastMigrationJobToFinish (file://<path>/node_modules/@libsql/client/lib-esm/migrations.js:97:30)
    at async HttpClient.execute (file://<path>/node_modules/@libsql/client/lib-esm/http.js:72:17)
    at async Object.query (<path>/node_modules/drizzle-kit/bin.cjs:119857:27)
    at async fromDatabase3 (<path>/node_modules/drizzle-kit/bin.cjs:22311:23)`
