### ISSUE TITLE
[BUG]: Incorrect Order of Operations in Migration Script Generation

### ISSUE THREAD

**Issue by rashmod** [drizzle-team/drizzle-kit-mirror#495]
I encountered an issue with the migration script generated by Drizzle-Kit when modifying the schema of my database tables. The problem arose from the incorrect order of operations, leading to errors during migration.

Current Schema:

Tables:
videos
video_state
upload_progress
transcode_progress
Initial Relationships:

video_state table had a unique video_id field.
upload_progress and transcode_progress tables referenced video_id from video_state as a foreign key.
Schema Changes:

Modified video_id in video_state to be a foreign key referencing the primary key in the videos table.
Updated the upload_progress and transcode_progress tables to reference the video_id from the videos table instead of video_state.
Problem:

When Drizzle-Kit generated the migration SQL script, it dropped the unique constraint on the video_id field in the video_state table before handling the foreign key dependencies in the upload_progress and transcode_progress tables. This caused an error since the upload_progress and transcode_progress tables were still dependent on the video_id in the video_state table.

Manual Fix:

I had to modify the order of operations in the migration script manually:

Dropped the foreign key constraints in the upload_progress and transcode_progress tables first.
Dropped the unique constraint in the video_state table.
Applied the new schema changes.
This approach resolved the issue, and the migration was successful.

Expected Behavior:

The generated migration script should handle the foreign key dependencies correctly by:

Dropping foreign key constraints in dependent tables (upload_progress and transcode_progress) before dropping the unique constraint in the video_state table.
Ensuring the order of operations prevents dependency-related errors during migration.
Additional Information:

Drizzle-Kit version: ^0.22.8
Database type: PostgreSQL

Error logged:
There is an issue with how the error logs are being printed, which was raised in a previous GitHub issue #491
``` shell
$ npm run db:migrate

> user_service@1.0.0 db:migrate
> drizzle-kit migrate --config=./src/config/drizzle.config.ts

drizzle-kit: v0.22.8
drizzle-orm: v0.31.2

←[90mCustom config path was provided, using './src/config/drizzle.config.ts'←[39m
←[90mReading config file 'C:\bhushan\Programming\web-dev-projects\youtube-clone\backend\user_service\src\config\drizzle.config.ts'←[39m
←[90mUsing 'pg' driver for database querying←[39m
[⣷] applying migrations...←[2K←[G[⣯] applying migrations...←[2K←[G[⣟] applying migrations...error: cannot drop constraint video_state_video_id_unique on table video_state because other objects depend on it
    at ←[90mC:\bhushan\Programming\web-dev-projects\youtube-clone\backend\user_service\←[39mnode_modules\←[4mdrizzle-kit←[24m\bin.cjs:77696:15
←[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)←[39m
    at <anonymous> ←[90m(C:\bhushan\Programming\web-dev-projects\youtube-clone\backend\user_service\←[39mnode_modules\←[4msrc←[24m\pg-core\dialect.ts:89:7←[90m)←[39m
    at NodePgSession.transaction ←[90m(C:\bhushan\Programming\web-dev-projects\youtube-clone\backend\user_service\←[39mnode_modules\←[4msrc←[24m\node-postgres\session.ts:155:19←[90m)←[39m
    at PgDialect.migrate ←[90m(C:\bhushan\Programming\web-dev-projects\youtube-clone\backend\user_service\←[39mnode_modules\←[4msrc←[24m\pg-core\dialect.ts:82:3←[90m)←[39m
    at migrate ←[90m(C:\bhushan\Programming\web-dev-projects\youtube-clone\backend\user_service\←[39mnode_modules\←[4msrc←[24m\node-postgres\migrator.ts:10:2←[90m)←[39m {
  length: ←[33m506←[39m,
  severity: ←[32m'ERROR'←[39m,
  code: ←[32m'2BP01'←[39m,
  detail: ←[32m'constraint transcoding_progress_video_id_video_state_video_id_fk on table transcoding_progress depends on index video_state_video_id_unique\n'←[39m +
    ←[32m'constraint upload_progress_video_id_video_state_video_id_fk on table upload_progress depends on index video_state_video_id_unique'←[39m,        
  hint: ←[32m'Use DROP ... CASCADE to drop the dependent objects too.'←[39m,
  position: ←[90mundefined←[39m,
  internalPosition: ←[90mundefined←[39m,
  internalQuery: ←[90mundefined←[39m,
  where: ←[90mundefined←[39m,
  schema: ←[90mundefined←[39m,
  table: ←[90mundefined←[39m,
  column: ←[90mundefined←[39m,
  dataType: ←[90mundefined←[39m,
  constraint: ←[90mundefined←[39m,
  file: ←[32m'dependency.c'←[39m,
  line: ←[32m'1204'←[39m,
  routine: ←[32m'reportDependentObjects'←[39m
}
```

**Comment by rashmod** [comment]
Faced the same issue when deleting a primary key field and assigning a different field as the primary. the SQL script generated was not working as it was generating 
It tried adding a new primary key to the table instead of first dropping the primary key and they added the new primary key

initial schema
```ts
export const videoStatus = pgEnum('video_status', [
	'UPLOADING',
	'TRANSCODING',
	'COMPLETED',
]);

const videoState = pgTable('video_state', {
	id: uuid('id').defaultRandom().primaryKey(),
	status: videoStatus('status').notNull().default('UPLOADING'),
	createdAt: timestamp('created_at', { mode: 'string' })
		.notNull()
		.defaultNow(),
	updatedAt: timestamp('updated_at', { mode: 'string' })
		.notNull()
		.defaultNow(),

	videoId: uuid('video_id')
		.notNull()
		.references(() => video.id),
});

export const videoStateRelations = relations(videoState, ({ one, many }) => ({
	video: one(video, { fields: [videoState.videoId], references: [video.id] }),
}));

// ----------------------

const uploadProgress = pgTable('upload_progress', {
	id: uuid('id').defaultRandom().primaryKey(),
	uploadId: varchar('upload_id', { length: 255 }).notNull(),
	uploadKey: varchar('upload_key', { length: 255 }).notNull(),
	totalParts: integer('total_parts').notNull(),
	uploadedParts: integer('uploaded_parts').notNull().default(0),
	createdAt: timestamp('created_at', { mode: 'string' })
		.notNull()
		.defaultNow(),
	updatedAt: timestamp('updated_at', { mode: 'string' })
		.notNull()
		.defaultNow(),

	videoId: uuid('video_id')
		.notNull()
		.references(() => video.id),
});

export const uploadProgressRelations = relations(uploadProgress, ({ one }) => ({
	video: one(video, {
		fields: [uploadProgress.videoId],
		references: [video.id],
	}),
}));

// ----------------------

export const transcodingStatus = pgEnum('transcoding_status', [
	'PENDING',
	'IN_PROGRESS',
	'COMPLETED',
]);

const transcodingProgress = pgTable('transcoding_progress', {
	id: uuid('id').defaultRandom().primaryKey(),
	status: transcodingStatus('status').notNull().default('PENDING'),
	createdAt: timestamp('created_at', { mode: 'string' })
		.notNull()
		.defaultNow(),
	updatedAt: timestamp('updated_at', { mode: 'string' })
		.notNull()
		.defaultNow(),

	videoId: uuid('video_id')
		.notNull()
		.references(() => video.id),
	resolutionId: uuid('resolution_id')
		.notNull()
		.references(() => resolution.id),
});

export const transcodingProgressRelations = relations(
	transcodingProgress,
	({ one }) => ({
		video: one(video, {
			fields: [transcodingProgress.videoId],
			references: [video.id],
		}),
		resolution: one(resolution, {
			fields: [transcodingProgress.resolutionId],
			references: [resolution.id],
		}),
	})
);
```

after making changes to the schema
```ts
const videoState = pgTable('video_state', {
	status: videoStatus('status').notNull().default('UPLOADING'),
	createdAt: timestamp('created_at', { mode: 'string' })
		.notNull()
		.defaultNow(),
	updatedAt: timestamp('updated_at', { mode: 'string' })
		.notNull()
		.defaultNow(),

	videoId: uuid('video_id')
		.notNull()
		.primaryKey()
		.references(() => video.id),
});

// ----------------------

const uploadProgress = pgTable('upload_progress', {
	uploadId: varchar('upload_id', { length: 255 }).notNull(),
	uploadKey: varchar('upload_key', { length: 255 }).notNull(),
	totalParts: integer('total_parts').notNull(),
	uploadedParts: integer('uploaded_parts').notNull().default(0),
	createdAt: timestamp('created_at', { mode: 'string' })
		.notNull()
		.defaultNow(),
	updatedAt: timestamp('updated_at', { mode: 'string' })
		.notNull()
		.defaultNow(),

	videoId: uuid('video_id')
		.notNull()
		.primaryKey()
		.references(() => video.id),
});

// ----------------------

const transcodingProgress = pgTable(
	'transcoding_progress',
	{
		status: transcodingStatus('status').notNull().default('PENDING'),
		createdAt: timestamp('created_at', { mode: 'string' })
			.notNull()
			.defaultNow(),
		updatedAt: timestamp('updated_at', { mode: 'string' })
			.notNull()
			.defaultNow(),

		videoId: uuid('video_id')
			.notNull()
			.references(() => video.id),
		resolutionId: uuid('resolution_id')
			.notNull()
			.references(() => resolution.id),
	},
	(transcodingProgress) => ({
		pk: primaryKey({
			columns: [
				transcodingProgress.videoId,
				transcodingProgress.resolutionId,
			],
		}),
	})
);
```

the migration script generated is
```sql
ALTER TABLE "upload_progress" ADD PRIMARY KEY ("video_id");--> statement-breakpoint
ALTER TABLE "video_state" ADD PRIMARY KEY ("video_id");--> statement-breakpoint
ALTER TABLE "transcoding_progress" ADD CONSTRAINT "transcoding_progress_video_id_resolution_id_pk" PRIMARY KEY("video_id","resolution_id");--> statement-breakpoint
ALTER TABLE "transcoding_progress" DROP COLUMN IF EXISTS "id";--> statement-breakpoint
ALTER TABLE "upload_progress" DROP COLUMN IF EXISTS "id";--> statement-breakpoint
ALTER TABLE "video_state" DROP COLUMN IF EXISTS "id";
```

I got the following error trying to migrate this
```bash
$ npm run db:migrate

> user_service@1.0.0 db:migrate
> drizzle-kit migrate --config=./src/config/drizzle.config.ts

drizzle-kit: v0.22.8
drizzle-orm: v0.31.2

←[90mCustom config path was provided, using './src/config/drizzle.config.ts'←[39m
←[90mReading config file 'C:\bhushan\Programming\web-dev-projects\youtube-clone\backend\user_service\src\config\drizzle.config.ts'←[39m
←[90mUsing 'pg' driver for database querying←[39m
[⣷] applying migrations...←[2K←[G[⣯] applying migrations...←[2K←[G[⣟] applying migrations...←[2K←[G[⡿] applying migrations...←[2K←[G[⢿] applying migrations...error: multiple primary keys for table "upload_progress" are not allowed
    at ←[90mC:\bhushan\Programming\web-dev-projects\youtube-clone\backend\user_service\←[39mnode_modules\←[4mdrizzle-kit←[24m\bin.cjs:77696:15
←[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)←[39m
    at <anonymous> ←[90m(C:\bhushan\Programming\web-dev-projects\youtube-clone\backend\user_service\←[39mnode_modules\←[4msrc←[24m\pg-core\dialect.ts:89:7←[90m)←[39m
    at NodePgSession.transaction ←[90m(C:\bhushan\Programming\web-dev-projects\youtube-clone\backend\user_service\←[39mnode_modules\←[4msrc←[24m\node-postgres\session.ts:155:19←[90m)←[39m
    at PgDialect.migrate ←[90m(C:\bhushan\Programming\web-dev-projects\youtube-clone\backend\user_service\←[39mnode_modules\←[4msrc←[24m\pg-core\dialect.ts:82:3←[90m)←[39m
    at migrate ←[90m(C:\bhushan\Programming\web-dev-projects\youtube-clone\backend\user_service\←[39mnode_modules\←[4msrc←[24m\node-postgres\migrator.ts:10:2←[90m)←[39m {
  length: ←[33m132←[39m,
  severity: ←[32m'ERROR'←[39m,
  code: ←[32m'42P16'←[39m,
  detail: ←[90mundefined←[39m,
  hint: ←[90mundefined←[39m,
  position: ←[90mundefined←[39m,
  internalPosition: ←[90mundefined←[39m,
  internalQuery: ←[90mundefined←[39m,
  where: ←[90mundefined←[39m,
  schema: ←[90mundefined←[39m,
  table: ←[90mundefined←[39m,
  column: ←[90mundefined←[39m,
  dataType: ←[90mundefined←[39m,
  constraint: ←[90mundefined←[39m,
  file: ←[32m'index.c'←[39m,
  line: ←[32m'223'←[39m,
  routine: ←[32m'index_check_primary_key'←[39m
}
```

after manually updating the SQL file to the following it worked
```sql
ALTER TABLE "transcoding_progress" DROP COLUMN IF EXISTS "id";--> statement-breakpoint
ALTER TABLE "upload_progress" DROP COLUMN IF EXISTS "id";--> statement-breakpoint
ALTER TABLE "video_state" DROP COLUMN IF EXISTS "id";--> statement-breakpoint
ALTER TABLE "upload_progress" ADD PRIMARY KEY ("video_id");--> statement-breakpoint
ALTER TABLE "video_state" ADD PRIMARY KEY ("video_id");--> statement-breakpoint
ALTER TABLE "transcoding_progress" ADD CONSTRAINT "transcoding_progress_video_id_resolution_id_pk" PRIMARY KEY("video_id","resolution_id");
```
