### ISSUE TITLE
drizzle-kit push ZodError: "expected": "'postgresql' | 'mysql' | 'sqlite'" but "received": "undefined",

### ISSUE THREAD

**Issue by knowmance** [drizzle-team/drizzle-kit-mirror#506]
Following the instructions here (https://orm.drizzle.team/docs/get-started-postgresql) I tried to create minimal setup of drizzle-kit and neon db. Seeing following error when I try push. Also cannot run drizzle studio.

**Error**
when I run `npx drizzle-kit push` I get 
```
drizzle-kit: v0.23.0
drizzle-orm: v0.32.0

No config path provided, using default path
Reading config file '<root>/drizzle.config.ts'
Using '@neondatabase/serverless' driver for database querying
 Warning  '@neondatabase/serverless' can only connect to remote Neon/Vercel Postgres/Supabase instances through a websocket
[⣽] Pulling schema from database...
ErrorEvent {
  [Symbol(kTarget)]: _WebSocket {
    _events: [Object: null prototype] {
      error: [Function],
      message: [Function],
      close: [Function],
      open: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'arraybuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: <Buffer >,
    _closeTimer: null,
    _errorEmitted: true,
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _autoPong: true,
    _url: '<url>',
    _req: null,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'error',
  [Symbol(kError)]: AggregateError
      at __node_internal_ (node:internal/errors:174:15)
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1177:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    [errors]: [ [Error], [Error], [Error], [Error], [Error], [Error] ]
  },
  [Symbol(kMessage)]: ''
```

When I run `npx drizzle-kit push --verbose`, I get

```
const error2 = new ZodError(ctx.common.issues);
                           ^

_ZodError: [
  {
    "expected": "'postgresql' | 'mysql' | 'sqlite'",
    "received": "undefined",
    "code": "invalid_type",
    "path": [
      "dialect"
    ],
    "message": "Required"
  }
]
    at get error [as error] (<root>/node_modules/drizzle-kit/bin.cjs:5186:28)
    at _ZodObject.parse (<root>/node_modules/drizzle-kit/bin.cjs:5266:22)
    at preparePushConfig (<root>/node_modules/drizzle-kit/bin.cjs:20374:33)
    at _Command.<anonymous> (<root>/node_modules/drizzle-kit/bin.cjs:131592:13) {
  issues: [
    {
      expected: "'postgresql' | 'mysql' | 'sqlite'",
      received: 'undefined',
      code: 'invalid_type',
      path: [ 'dialect' ],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      expected: "'postgresql' | 'mysql' | 'sqlite'",
      received: 'undefined',
      code: 'invalid_type',
      path: [ 'dialect' ],
      message: 'Required'
    }
  ]
}

Node.js v20.10.0
```

my db.ts
```
import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
import { config } from "dotenv";

config({ path: ".env" });

const sql = neon(process.env.DATABASE_URL!);
export const db = drizzle(sql);
```

my schema.ts
```
import { integer, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core';

export const usersTable = pgTable('users_table', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  age: integer('age').notNull(),
  email: text('email').notNull().unique(),
});

export const postsTable = pgTable('posts_table', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  content: text('content').notNull(),
  userId: integer('user_id')
    .notNull()
    .references(() => usersTable.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at')
    .notNull()
    .$onUpdate(() => new Date()),
});

export type InsertUser = typeof usersTable.$inferInsert;
export type SelectUser = typeof usersTable.$inferSelect;

export type InsertPost = typeof postsTable.$inferInsert;
export type SelectPost = typeof postsTable.$inferSelect;
```

My package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "@neondatabase/serverless": "^0.9.4",
    "dotenv": "^16.4.5",
    "drizzle-orm": "^0.32.0"
  },
  "devDependencies": {
    "drizzle-kit": "^0.23.0"
  }
}
```

my .env
`DATABASE_URL=<valid_neon_url>`

I know the DATABASE_URL is valid because when I run `psql <valid_neon_url>` I can connect the database successfully.

my drizzle.config.ts

```
import { config } from 'dotenv';
import { defineConfig } from "drizzle-kit";

config({ path: '.env' });

export default defineConfig({
  schema: "./schema.ts",
  out: "./migrations",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
});

```

**Comment by barrynorman** [comment]
I don't have the same issue but a similar. 
Suddenly the drizzle config throws an error when trying to introspect.

```
 errors: [
    {
      code: 'invalid_type',
      expected: 'object',
      received: 'string',
      path: [ 'database' ],
      message: 'Expected object, received string'
    }
  ]
```

**Comment by tehnorm** [comment]
I am seeing the same thing with a postgres using the expanded `dbCredentials` syntax as @barrynorman .

**Comment by knowmance** [comment]
The issue automatically fixed for me. The only thing I can relate to is I flew to a different country (out of Vietnam, where I was seeing the issue) so may be it was related to firewall or something.

**Comment by knowmance** [comment]
The issue just appeared again for no apparent reason that I can connect to. Wondering if it is linked to some network setting? Anyone in the same boat? Things that I have tried:
1) restart computer / router / use different wifi and phone hotspot
2) Same code from a remote desktop in USA works fine (currently I am in India)

**Comment by knowmance** [comment]
More info: The same code with the same database connection works fine when pushed to vercel Preview environment. Something must be wrong with my local setup that I am not able to figure out after all attempts (cleared .next cache, restarts, laptop DNS cache, chrome cache etc).

My development is completely stopped. Will highly appreciate any pointers. Thank you.

**Comment by knowmance** [comment]
With help from AI I resolved the issue. It was linked to my DNS setup. I was using Google and changed to Cloudflare. The steps that worked:

Change to Cloudflare DNS:
Copysudo networksetup -setdnsservers Wi-Fi 1.1.1.1 1.0.0.1

Flush the DNS cache:
Copysudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder
