### ISSUE TITLE
`drizzle-kit generate` introduce a ReferenceError

### ISSUE THREAD

**Issue by AhmedBaset** [drizzle-team/drizzle-kit-mirror#518]
The generated migration is

```sql
ALTER TYPE "access_rights" ADD VALUE 'EMPLOYEE';--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "access_rights" SET DEFAULT EMPLOYEE;
```

When I tried to migrate:

```bash
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^

PostgresError: cannot use column reference in DEFAULT expression
    at ErrorResponse (file:///A:/projects/xxxxxxxx/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:788:26)
    at handle (file:///A:/projects/xxxxxxxxxxx/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:474:6)
    at Socket.data (file:///A:/projects/55-sanaye/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/connection.js:315:9)
```

the schema:

```js
const Users = pgTable("users", {
  // ...
  accessRights: accessRightsEnum("access_rights")
    .array()
    .notNull()
    .default(["EMPLOYEE"]),
});
```

I don't have much experience in sql, but GPT suggested this version and it worked:
```sql
ALTER TABLE "users" ALTER COLUMN "access_rights" SET DEFAULT ARRAY['EMPLOYEE'::access_rights];
```

**Comment by L-Mario564** [comment]
This should be fixed in latest. If you're still experiencing this issue, feel free to open a new issue on the main repo: https://github.com/drizzle-team/drizzle-orm/issues.
