### ISSUE TITLE
getaddrinfo ENOTFOUND rds-data.eu-north-1.amazonaws.com

### ISSUE THREAD

**Issue by sercamembert** [drizzle-team/drizzle-kit-mirror#534]
Error: getaddrinfo ENOTFOUND rds-data.eu-north-1.amazonaws.com
    at $ (https://local.drizzle.studio/index.js:12885:10688)
    at async https://local.drizzle.studio/index.js:12885:10833
    at async Promise.all (index 0)
    at async _Dt (https://local.drizzle.studio/index.js:12696:1529)
    at async QRl (https://local.drizzle.studio/index.js:12885:10814)
    
    
[bug-report.zip](https://github.com/user-attachments/files/16530604/bug-report.zip)

**Comment by L-Mario564** [comment]
This seems to be an issue with the credentials you've provided in the Drizzle config file. Make sure the credentials are correct before connecting to Studio.
