### ISSUE TITLE
Error: SQL_PARSE_ERROR: SQL string could not be parsed: near LIMIT, "None": syntax error at (1, 112)

### ISSUE THREAD

**Issue by danielo515** [drizzle-team/drizzle-kit-mirror#545]
I'm getting this error in the turso drizzle studio, for anything I do:

```
Error: SQL_PARSE_ERROR: SQL string could not be parsed: near LIMIT, "None": syntax error at (1, 112)
    at window.drizzle (https://turso.tech/_next/static/chunks/7061-76f02d7fd6797fe1.js:1:28549)
    at async eie.all (https://turso.tech/_next/static/chunks/74f8cf84.7806e5c7c0c51970.js:12091:6187)
    at async https://turso.tech/_next/static/chunks/74f8cf84.7806e5c7c0c51970.js:12091:3544
    at async fetchRecords (https://turso.tech/_next/static/chunks/74f8cf84.7806e5c7c0c51970.js:25:19669)
    at async deleteRecords (https://turso.tech/_next/static/chunks/74f8cf84.7806e5c7c0c51970.js:25:20550)
    at async https://turso.tech/_next/static/chunks/74f8cf84.7806e5c7c0c51970.js:144:7618

```

The operations, however, suceeded:

```json
{
  "drizzle-playground": {
    "state": {
      "editorHight": 300,
      "currentFile": "sql",
      "drizzleValue": null,
      "sqlValue": "UPDATE\n  \"tokens\"\nSET \nexpiresAt=1735686000000;",
      "showRecordsAsJson": true,
      "drizzleResult": "{\"json\":null}",
      "sqlResult": "{\"json\":{\"status\":\"success\",\"records\":null,\"executionTime\":96.59999990463257}}"
    },
    "version": 0
  },
  "drizzle-version": "2.0.1",
  "drizzle-global": {
    "state": {
      "showCounts": false
    },
    "version": 0
  },
  "drizzle-db-temp": {
    "state": {
      "styleMode": "default",
      "currentPage": "main",
      "filterViews": {},
      "isSidebarOpen": true,
      "isShowSidebarContent": true,
      "filtersVisible": false,
      "sidebarWidth": 268,
      "currentSchema": {
        "name": "public",
        "tables": [],
        "views": []
      },
      "currentTable": {
        "name": "apiExpenses",
        "columns": [
          {
            "name": "amount",
            "type": "string",
            "hasDefault": false,
            "hasCustomDefault": false,
            "notNull": false,
            "_type": "real",
            "width": 120,
            "visible": true
          },
          {
            "name": "currency",
            "type": "string",
            "hasDefault": false,
            "hasCustomDefault": false,
            "notNull": false,
            "_type": "text",
            "width": 120,
            "visible": true
          },
          {
            "name": "createdAt",
            "type": "number",
            "default": "(CURRENT_TIMESTAMP)",
            "hasDefault": true,
            "hasCustomDefault": false,
            "notNull": true,
            "_type": "integer",
            "width": 135,
            "visible": true
          },
          {
            "name": "source",
            "type": "string",
            "hasDefault": false,
            "hasCustomDefault": false,
            "notNull": false,
            "_type": "text",
            "width": 120,
            "visible": true
          },
          {
            "name": "data",
            "type": "string",
            "hasDefault": false,
            "hasCustomDefault": false,
            "notNull": false,
            "_type": "text",
            "width": 120,
            "visible": true
          }
        ],
        "primaryKeys": [],
        "type": "table",
        "id": "apiExpenses",
        "relations": [],
        "filters": [],
        "sort": null,
        "pagination": {
          "limit": 50,
          "offset": 0
        },
        "records": [],
        "createdRecords": [],
        "editedFields": [],
        "schema": "public",
        "historyId": "REDACTED",
        "executionTime": 63.90000009536743
      }
    },
    "version": 0
  }
}
```

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3252.
