### ISSUE TITLE
Studio

### ISSUE THREAD

**Issue by GitHubFoxy** [drizzle-team/drizzle-kit-mirror#558]
Error: There is not enough information to infer relation "__public__.cart.items"
    at https://local.drizzle.studio/index.js:14119:428
    at async hkl (https://local.drizzle.studio/index.js:14122:32452)
    
    {
  "drizzle-playground": {
    "state": {
      "currentFile": "sql",
      "drizzleValue": null,
      "sqlValue": null,
      "showRecordsAsJson": false,
      "drizzleResult": "{\"json\":null}",
      "sqlResult": "{\"json\":null}"
    },
    "version": 0
  },
  "drizzle-global": {
    "state": {
      "showCounts": true,
      "flatSchemas": false
    },
    "version": 0
  },
  "drizzle-version": "2.0.1",
  "drizzle-custom-theme-ids": []
}

**Comment by GitHubFoxy** [comment]
It said to report problems so i reported, new dev so sorry if im wrong or smth

i deleted all migrations, generate new one, migrated, and still cant access Drizzle studio. Arc browser
