### ISSUE TITLE
error in running drizzle studio

### ISSUE THREAD

**Issue by akash827182** [drizzle-team/drizzle-kit-mirror#562]
Error
    at le (https://local.drizzle.studio/index.js:14122:33444)
    at async https://local.drizzle.studio/index.js:14122:33591
    at async Promise.all (index 0)
    at async voi (https://local.drizzle.studio/index.js:13939:1476)
    at async hkl (https://local.drizzle.studio/index.js:14122:33572)

schema:
import { serial, text, timestamp, pgTable } from "drizzle-orm/pg-core";

export const user = pgTable("user", {
  id: serial("id"),
  name: text("name"),
  email: text("email"),
  password: text("password"),
  role: text("role").$type<"admin" | "customer">(),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
}); 

   
Include Drizzle local storage
{
  "drizzle-playground": {
    "state": {
      "currentFile": "sql",
      "drizzleValue": null,
      "sqlValue": null,
      "showRecordsAsJson": false,
      "drizzleResult": "{\"json\":null}",
      "sqlResult": "{\"json\":null}"
    },
    "version": 0
  },
  "drizzle-global": {
    "state": {
      "showCounts": true,
      "flatSchemas": false
    },
    "version": 0
  },
  "drizzle-version": "2.0.1",
  "drizzle-custom-theme-ids": [],
  "drizzle-db-63ea54026f1e03e0de749053b1bce181766b22482dafee2a11671e07ee1a2688": {
    "state": {
      "styleMode": "default",
      "currentPage": "main",
      "filterViews": {},
      "isSidebarOpen": true,
      "isShowSidebarContent": true,
      "filtersVisible": false,
      "sidebarWidth": 268,
      "currentSchema": {
        "name": "public",
        "tables": [],
        "views": []
      },
      "currentTable": null
    },
    "version": 0
  }
}

**Comment by L-Mario564** [comment]
If you keep facing this issue, please file a new issue over on the [main repo](https://github.com/drizzle-team/drizzle-orm/issues), provide the error message that's shown as well as steps to reproduce this bug
