### ISSUE TITLE
Error: global is not defined - when deploying nuxt app using nuxthub

### ISSUE THREAD

**Issue by rscorer** [drizzle-team/drizzle-kit-mirror#566]
Hi, this app runs locally, but when i go to deploy on Cloudflare using NuxtHub I get a 500 error, this page is temporarily unavailable. When I try to look at my database in the NuxtHub dashboard, I get this error

```
Error: global is not defined
    at window.drizzle (https://admin.hub.nuxt.com/_nuxt/CgE_bnhu.js:34:300)
    at async o (https://admin.hub.nuxt.com/_nuxt/_dpJR7ZA.js:13439:6850)
    at async https://admin.hub.nuxt.com/_nuxt/_dpJR7ZA.js:13439:7022
    at async Promise.all (index 2)
    at async Tot (https://admin.hub.nuxt.com/_nuxt/_dpJR7ZA.js:13379:1111)
    at async Pot (https://admin.hub.nuxt.com/_nuxt/_dpJR7ZA.js:13439:7004)


```
[Bug Report from NuxtHub (1).zip](https://github.com/user-attachments/files/16977553/Bug.Report.from.NuxtHub.1.zip)

**Comment by rscorer** [comment]
After further research, I think this is simply a bad build from nuxthub which isn't even creating any of the database, or other cloudflare requirements. I'll close this
