### ISSUE TITLE
drizzle-studio: S.UPDATE_RULE.toLowerCase is not a function

### ISSUE THREAD

**Issue by ubinatus** [drizzle-team/drizzle-kit-mirror#575]
Hi Team, we cannot longer run drizzle studio. Just sharing the error stack trace. We have over 25 tables so sharing the schema here will be a mess.

**stacktrace**
```txt
TypeError: S.UPDATE_RULE.toLowerCase is not a function
    at https://local.drizzle.studio/index.js:13913:1267
    at Array.map (<anonymous>)
    at https://local.drizzle.studio/index.js:13913:1115
    at Array.map (<anonymous>)
    at xoi (https://local.drizzle.studio/index.js:13913:233)
    at async ykl (https://local.drizzle.studio/index.js:14123:33525)
```

**localstorage**
```json
{
  "drizzle-playground": {
    "state": {
      "currentFile": "sql",
      "drizzleValue": null,
      "sqlValue": null,
      "showRecordsAsJson": false,
      "drizzleResult": "{\"json\":null}",
      "sqlResult": "{\"json\":null}"
    },
    "version": 0
  },
  "drizzle-global": {
    "state": {
      "showCounts": true,
      "flatSchemas": false,
      "dataFormats": null
    },
    "version": 0
  },
  "drizzle-version": "2.0.1",
  "drizzle-custom-theme-ids": []
}
```

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3212.
