### ISSUE TITLE
BigInt column with default value throws `TypeError: Do not know how to serialize a BigInt`

### ISSUE THREAD

**Issue by TheDevMinerTV** [drizzle-team/drizzle-kit-mirror#581]
Schema:
```ts
import { bigint, pgTable, serial } from 'drizzle-orm/pg-core';

export const usage = pgTable('usages', {
  id: serial('id').primaryKey(),
  usage: bigint('usage', { mode: 'bigint' }).default(0n),
});
```

Error:
```
$ drizzle-kit generate

No config path provided, using default 'drizzle.config.ts'
Reading config file 'drizzle.config.ts'
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at diffSchemasOrTables (node_modules/.pnpm/drizzle-kit@0.24.2/node_modules/drizzle-kit/bin.cjs:22431:27)
    at applyPgSnapshotsDiff (node_modules/.pnpm/drizzle-kit@0.24.2/node_modules/drizzle-kit/bin.cjs:26264:26)
    at async prepareAndMigratePg (node_modules/.pnpm/drizzle-kit@0.24.2/node_modules/drizzle-kit/bin.cjs:28738:42)
    at async Object.handler (node_modules/.pnpm/drizzle-kit@0.24.2/node_modules/drizzle-kit/bin.cjs:83523:7)
    at async run (node_modules/.pnpm/drizzle-kit@0.24.2/node_modules/drizzle-kit/bin.cjs:82064:7)
```

**Comment by krishna-makwana** [comment]
To serialize a bigint value use bigserial
refer: https://orm.drizzle.team/docs/column-types/pg#bigserial
![drizzle-screenshot-1](https://github.com/user-attachments/assets/ba3d310f-1eab-4ef7-9be3-86e80dfefb85)

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/1879 over on the main repo.
