### ISSUE TITLE
error on drizzle-kit migrate with planetscale

### ISSUE THREAD

**Issue by pdeva** [drizzle-team/drizzle-kit-mirror#597]
getting this error:

```
npx drizzle-kit migrate

No config path provided, using default 'drizzle.config.ts'
Reading config file '/Users/pdeva/code/monorepo/web/dashboard/drizzle.config.ts'
[⣷] applying migrations...TypeError: Cannot read properties of undefined (reading 'fetch')
    at new Connection (file:///Users/pdeva/code/monorepo/web/dashboard/node_modules/.pnpm/@planetscale+database@1.19.0/node_modules/@planetscale/database/dist/index.js:47:29)
    at Client.connection (file:///Users/pdeva/code/monorepo/web/dashboard/node_modules/.pnpm/@planetscale+database@1.19.0/node_modules/@planetscale/database/dist/index.js:26:16)
    at Client.execute (file:///Users/pdeva/code/monorepo/web/dashboard/node_modules/.pnpm/@planetscale+database@1.19.0/node_modules/@planetscale/database/dist/index.js:23:21)
    at PlanetScalePreparedQuery.execute (/Users/pdeva/code/monorepo/web/dashboard/node_modules/.pnpm/drizzle-orm@0.35.1_@planetscale+database@1.19.0_@types+react@18.3.11_react@18.3.1/node_modules/src/planetscale-serverless/session.ts:58:29)
    at PlanetscaleSession.execute (/Users/pdeva/code/monorepo/web/dashboard/node_modules/.pnpm/drizzle-orm@0.35.1_@planetscale+database@1.19.0_@types+react@18.3.11_react@18.3.1/node_modules/src/mysql-core/session.ts:84:5)
    at MySqlDialect.migrate (/Users/pdeva/code/monorepo/web/dashboard/node_modules/.pnpm/drizzle-orm@0.35.1_@planetscale+database@1.19.0_@types+react@18.3.11_react@18.3.1/node_modules/src/mysql-core/dialect.ts:62:17)
    at migrate (/Users/pdeva/code/monorepo/web/dashboard/node_modules/.pnpm/drizzle-orm@0.35.1_@planetscale+database@1.19.0_@types+react@18.3.11_react@18.3.1/node_modules/src/planetscale-serverless/migrator.ts:11:19)
    at migrateFn (/Users/pdeva/code/monorepo/web/dashboard/node_modules/.pnpm/drizzle-kit@0.26.2/node_modules/drizzle-kit/bin.cjs:64291:18)
    at Object.handler (/Users/pdeva/code/monorepo/web/dashboard/node_modules/.pnpm/drizzle-kit@0.26.2/node_modules/drizzle-kit/bin.cjs:87137:11)
    at async run (/Users/pdeva/code/monorepo/web/dashboard/node_modules/.pnpm/drizzle-kit@0.26.2/node_modules/drizzle-kit/bin.cjs:85613:7)
```
   
`drizzle.config.ts`
```ts
import 'dotenv/config';
import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  out: './drizzle',
  schema: './src/db/schema.ts',
  dialect: 'mysql',
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
});
```

```
node --version
v22.5.1

drizzle-orm": "^0.35.1",
"drizzle-kit": "^0.26.2",
```

note that `push` works fine.

```
npx drizzle-kit push
No config path provided, using default 'drizzle.config.ts'
Reading config file '/Users/pdeva/code/monorepo/web/dashboard/drizzle.config.ts'
[✓] Pulling schema from database...
Reading schema files:
/Users/pdeva/code/monorepo/web/dashboard/src/db/schema.ts

[✓] Changes applied
```

its just `migrate` that has this problem...

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3233.
