### ISSUE TITLE
drizzle-kit migrate fails on documentation example for seed-users

### ISSUE THREAD

**Issue by isimmons** [drizzle-team/drizzle-kit-mirror#600]
I'm just learning how to use drizzle-kit.

using sqlite

I can generate and migrate a users table but when I follow the docs for a custom seed-users migration and then try to run drizzle-kit migrate, I get the following error.

```bash
npx drizzle-kit migrate
No config path provided, using default 'drizzle.config.ts'
Reading config file 'C:\Users\isimm\code\React\comp-test-ground\drizzle.config.ts'
[⣷] applying migrations...DrizzleError: Failed to run the query '-- Custom SQL migration file, put you code below! --

INSERT INTO "users" ("name") VALUES('Dan');
INSERT INTO "users" ("name") VALUES('Andrew');
INSERT INTO "users" ("name") VALUES('Dane');'
    at BetterSQLiteSession.run (C:\Users\isimm\code\React\comp-test-ground\node_modules\.pnpm\drizzle-orm@0.35.1_@types+react@18.3.11_better-sqlite3@11.3.0_react@18.3.1\node_modules\src\sqlite-core\session.ts:148:10)
    at SQLiteSyncDialect.migrate (C:\Users\isimm\code\React\comp-test-ground\node_modules\.pnpm\drizzle-orm@0.35.1_@types+react@18.3.11_better-sqlite3@11.3.0_react@18.3.1\node_modules\src\sqlite-core\dialect.ts:798:15)
    ... 3 lines matching cause stack trace ...
    at async run (C:\Users\isimm\code\React\comp-test-ground\node_modules\.pnpm\drizzle-kit@0.26.2\node_modules\drizzle-kit\bin.cjs:85613:7) {    
  cause: RangeError: The supplied SQL string contains more than one statement
      at Database.prepare (C:\Users\isimm\code\React\comp-test-ground\node_modules\.pnpm\better-sqlite3@11.3.0\node_modules\better-sqlite3\lib\methods\wrappers.js:5:21)
      at BetterSQLiteSession.prepareQuery (C:\Users\isimm\code\React\comp-test-ground\node_modules\.pnpm\drizzle-orm@0.35.1_@types+react@18.3.11_better-sqlite3@11.3.0_react@18.3.1\node_modules\src\better-sqlite3\session.ts:50:28)
      at BetterSQLiteSession.prepareOneTimeQuery (C:\Users\isimm\code\React\comp-test-ground\node_modules\.pnpm\drizzle-orm@0.35.1_@types+react@18.3.11_better-sqlite3@11.3.0_react@18.3.1\node_modules\src\sqlite-core\session.ts:135:15)
      at BetterSQLiteSession.run (C:\Users\isimm\code\React\comp-test-ground\node_modules\.pnpm\drizzle-orm@0.35.1_@types+react@18.3.11_better-sqlite3@11.3.0_react@18.3.1\node_modules\src\sqlite-core\session.ts:146:16)
      at SQLiteSyncDialect.migrate (C:\Users\isimm\code\React\comp-test-ground\node_modules\.pnpm\drizzle-orm@0.35.1_@types+react@18.3.11_better-sqlite3@11.3.0_react@18.3.1\node_modules\src\sqlite-core\dialect.ts:798:15)
      at migrate (C:\Users\isimm\code\React\comp-test-ground\node_modules\.pnpm\drizzle-orm@0.35.1_@types+react@18.3.11_better-sqlite3@11.3.0_react@18.3.1\node_modules\src\better-sqlite3\migrator.ts:10:13)
      at migrateFn (C:\Users\isimm\code\React\comp-test-ground\node_modules\.pnpm\drizzle-kit@0.26.2\node_modules\drizzle-kit\bin.cjs:64448:18)   
      at Object.handler (C:\Users\isimm\code\React\comp-test-ground\node_modules\.pnpm\drizzle-kit@0.26.2\node_modules\drizzle-kit\bin.cjs:87148:11)
      at async run (C:\Users\isimm\code\React\comp-test-ground\node_modules\.pnpm\drizzle-kit@0.26.2\node_modules\drizzle-kit\bin.cjs:85613:7)    
}
``` 

This error in the stack stands out. `RangeError: The supplied SQL string contains more than one statement`

## package.json versions

```json
"better-sqlite3": "^11.3.0",
"drizzle-kit": "^0.26.2",
"drizzle-orm": "^0.35.1",
```

## drizzle.config.ts
```ts
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  out: './drizzle',
  dialect: 'sqlite',
  schema: './src/database/schemas/*',
  dbCredentials: {
    url: './src/database/appdata.sqlite',
  },
})
```

##users schema

```ts
import { sqliteTable, integer, text } from 'drizzle-orm/sqlite-core'

export const users = sqliteTable('users', {
  id: integer('id').primaryKey(),
  name: text('name', { length: 255 }),
})
```

## migrations

init:

```sql
CREATE TABLE `users` (
	`id` integer PRIMARY KEY NOT NULL,
	`name` text(255)
);
```

seed-users

```sql
-- Custom SQL migration file, put you code below! --

INSERT INTO "users" ("name") VALUES('Dan');
INSERT INTO "users" ("name") VALUES('Andrew');
INSERT INTO "users" ("name") VALUES('Dane');
```

**Comment by isimmons** [comment]
Ok writing this as a single statement works.

```sql
INSERT INTO "users" (name) 
VALUES 
    ('Dan'),
    ('Andrew'),
    ('Dane');
```

I don't know, is this a difference in sqlite vs pg or is it a bug in drizzle-kit handling multiple statements?

**Comment by L-Mario564** [comment]
Not officially documented, but here's a resource on why this happens: https://www.answeroverflow.com/m/1193324770092134430.

**Comment by L-Mario564** [comment]
Nevermind, found an official resource: https://orm.drizzle.team/docs/drizzle-config-file#breakpoints.
