### ISSUE TITLE
AWS Data Api - migrate - Cannot destructure property 'resourceArn' of 'connection' as it is undefined

### ISSUE THREAD

**Issue by dubscode** [drizzle-team/drizzle-kit-mirror#606]
```
wisedan@ML-N96CF5J61F bestrev_backend % npx drizzle-kit migrate
No config path provided, using default 'drizzle.config.ts'
Reading config file '/Users/wisedan/bestrev/bestrev_backend/drizzle.config.ts'
db name -----
resourceArn arn:aws:rds:-----------
secretArn arn:aws:secretsmanager:---------
**TypeError: Cannot destructure property 'resourceArn' of 'connection' as it is undefined.**
    at drizzle (/Users/wisedan/bestrev/bestrev_backend/node_modules/src/aws-data-api/pg/driver.ts:171:10)
    at preparePostgresDB (/Users/wisedan/bestrev/bestrev_backend/node_modules/drizzle-kit/bin.cjs:64043:22)
    at async Object.handler (/Users/wisedan/bestrev/bestrev_backend/node_modules/drizzle-kit/bin.cjs:87123:39)
    at async run (/Users/wisedan/bestrev/bestrev_backend/node_modules/drizzle-kit/bin.cjs:85613:7)
```

drizzle.config.ts
```
import 'dotenv/config';

import { defineConfig } from 'drizzle-kit';

console.log(process.env.RDS_DB_NAME);
console.log(process.env.RDS_DB_CLUSTER_ARN);
console.log(process.env.RDS_DB_SECRET_ARN);

export default defineConfig({
  dialect: 'postgresql',
  dbCredentials: {
    // url: process.env.DATABASE_URL || 'no-database-url-set',
    database: process.env.RDS_DB_NAME || 'no-database-name-set',
    resourceArn: 'no-cluster-arn-set',
    secretArn: process.env.RDS_DB_SECRET_ARN || 'no-secret-set',
  },
  driver: 'aws-data-api',
  schema: './packages/core/src/drizzle/schema',
  out: './packages/core/src/drizzle/migrations',
  introspect: {
    casing: 'camel',
  },
});
```

package versions:
```
 ├── @aws-sdk/client-rds-data@3.677.0
│ ├── @faker-js/faker@8.4.1
│ ├── @types/lodash@4.14.202
│ ├── @types/node@20.11.24
│ ├── @types/pg@8.11.10 deduped
│ ├── dayjs@1.11.10
│ ├── drizzle-kit@0.26.2
│ ├── drizzle-orm@0.35.3
│ ├── graphql-tag@2.12.6
│ ├── jsdom@24.1.0
│ ├── lodash@4.17.21 deduped
│ ├── pg@8.13.0
│ ├── sst@2.41.4 deduped
│ └── vitest@1.6.0
```

Another issue speculated there might be some missing parts for the data api: #605 

Let me know if there is anything else helpful I could provide, and thank you for your time.

**Comment by L-Mario564** [comment]
We'll keep track of this issue over on the main repo: https://github.com/drizzle-team/drizzle-orm/issues/3224.
