### ISSUE TITLE
Erro: connect ECONNREFUSED 127.0.0.1:5432

### ISSUE THREAD

**Issue by JMMabui** [drizzle-team/drizzle-kit-mirror#610]
Error: connect ECONNREFUSED 127.0.0.1:5432
    at _ (https://local.drizzle.studio/index.js:14138:33349)
    at async https://local.drizzle.studio/index.js:14138:33539
    at async Promise.all (index 0)
    at async $oi (https://local.drizzle.studio/index.js:13940:1587)
    at async Xkl (https://local.drizzle.studio/index.js:14138:33520)
[bug-report (1).zip](https://github.com/user-attachments/files/17573736/bug-report.1.zip)

**Comment by L-Mario564** [comment]
You can't access Studio via localhost.
