### ISSUE TITLE
Error while pushing changes

### ISSUE THREAD

**Issue by MartelliEnrico** [drizzle-team/drizzle-kit-mirror#67]
While executing a push:mysql command, I received this error:

```
TypeError: Cannot read properties of undefined (reading 'compositePrimaryKeys')
    at ./node_modules/drizzle-kit/index.js:25898:51
    at Array.map (<anonymous>)
    at prepareDeleteCompositePrimaryKeyMySql (./node_modules/drizzle-kit/index.js:25893:33)
    at ./node_modules/drizzle-kit/index.js:26200:33
    at Array.forEach (<anonymous>)
    at applySnapshotsDiff (./node_modules/drizzle-kit/index.js:26160:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async prepareSQL (./node_modules/drizzle-kit/index.js:24027:14)
    at async prepareMySQLPush (./node_modules/drizzle-kit/index.js:23886:47)
    at async Command2.<anonymous> (./node_modules/drizzle-kit/index.js:51134:22)
```

The deployed schema has a composite primary key, while the new schema that I'm trying to push has a new primary key.

**Comment by AndriiSherman** [comment]
checking that

**Comment by AndriiSherman** [comment]
can you share a version of drizzle-kit you are using?

**Comment by AndriiSherman** [comment]
Thanks, let me test it locally

**Comment by dylanirion** [comment]
I am also running into this on `generate:mysql` when trying to rename a table with a composite primary key

**Comment by AndriiSherman** [comment]
Could you please check your setup with 0.19.0 release? Please check release notes for breaking changes instructions

**Comment by MartelliEnrico** [comment]
I think I'm seeing the exact problem still

```
drizzle-kit: v0.19.0
drizzle-orm: v0.27.0

No config path provided, using default 'drizzle.config.ts'
Reading config file './drizzle.config.ts'
Reading schema files:
./src/server/db/schema.ts

~ Account › accounts table will be renamed
~ Recipe › recipes table will be renamed
~ Session › sessions table will be renamed
~ User › users table will be renamed
~ VerificationToken › verification_tokens table will be renamed
--- all table conflicts resolved ---


+ id column will be created

~ userId › user_id column will be renamed

+ oauth_token_secret column will be created

+ oauth_token column will be created

+ created_at column will be created

+ updated_at column will be created
--- all columns conflicts in accounts table resolved ---


~ authorId › author_id column will be renamed
--- all columns conflicts in recipes table resolved ---


+ id column will be created

~ userId › user_id column will be renamed

+ created_at column will be created

+ updated_at column will be created
--- all columns conflicts in sessions table resolved ---


~ emailVerified › email_verified column will be renamed

+ created_at column will be created

+ updated_at column will be created
--- all columns conflicts in users table resolved ---

TypeError: Cannot read properties of undefined (reading 'compositePrimaryKeys')
    at ./node_modules/drizzle-kit/index.cjs:10506:51
    at Array.map (<anonymous>)
    at prepareDeleteCompositePrimaryKeyMySql (./node_modules/drizzle-kit/index.cjs:10501:33)
    at ./node_modules/drizzle-kit/index.cjs:10813:33
    at Array.forEach (<anonymous>)
    at applySnapshotsDiff (./node_modules/drizzle-kit/index.cjs:10769:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async prepareSQL (./node_modules/drizzle-kit/index.cjs:8550:14)
    at async prepareMySQLPush (./node_modules/drizzle-kit/index.cjs:8389:47)
    at async Command.<anonymous> (./node_modules/drizzle-kit/index.cjs:46177:22)
```

**Comment by AndriiSherman** [comment]
Could you please share a schema you want to push and a schema you have? Maybe a minimal reproducible example you can find?
Maybe some edge case I can't still reproduce. Looking into the number of renames you have, seems like a major schema changes is going to be applied

**Comment by MartelliEnrico** [comment]
Sure, no problem. Here's the schema.ts file:
```typescript
import { relations } from "drizzle-orm";
import {
  datetime,
  mysqlEnum,
  mysqlTable,
  text,
  uniqueIndex,
  varchar,
  bigint as mysqlBigint,
  index,
} from "drizzle-orm/mysql-core";

const string = (name: string, length = 255) => varchar(name, { length });
const bigint = (name: string) => mysqlBigint(name, { mode: "bigint" });

export const recipes = mysqlTable("recipes", {
  id: bigint("id").autoincrement().primaryKey(),
  authorId: bigint("author_id"),
  title: string("title").notNull(),
  status: mysqlEnum("status", ["DRAFT", "PUBLISHED"]).default("DRAFT"),
});

export const recipesRelations = relations(recipes, ({ one }) => ({
  author: one(users, { fields: [recipes.authorId], references: [users.id] }),
}));

export const users = mysqlTable(
  "users",
  {
    id: bigint("id").autoincrement().primaryKey(),
    name: string("name"),
    email: string("email"),
    emailVerified: datetime("email_verified", { fsp: 6 }),
    image: string("image"),
    createdAt: datetime("created_at").notNull(),
    updatedAt: datetime("updated_at").notNull(),
  },
  (users) => ({
    email: uniqueIndex("email").on(users.email),
  })
);

export const usersRelations = relations(users, ({ many }) => ({
  recipes: many(recipes),
}));

export const accounts = mysqlTable(
  "accounts",
  {
    id: bigint("id").autoincrement().primaryKey(),
    userId: bigint("user_id"),
    type: string("type").notNull(),
    provider: string("provider").notNull(),
    providerAccountId: string("providerAccountId").notNull(),
    refreshToken: string("refresh_token"),
    accessToken: string("access_token"),
    expiresAt: bigint("expires_at"),
    tokenType: string("token_type"),
    scope: string("scope"),
    idToken: text("id_token"),
    sessionState: string("session_state"),
    oauthTokenSecret: string("oauth_token_secret"),
    oauthToken: string("oauth_token"),
    createdAt: datetime("created_at").notNull(),
    updatedAt: datetime("updated_at").notNull(),
  },
  (accounts) => ({
    userId: index("user_id").on(accounts.userId),
  })
);

export const sessions = mysqlTable(
  "sessions",
  {
    id: bigint("id").autoincrement().primaryKey(),
    userId: bigint("user_id").notNull(),
    expires: datetime("expires", { fsp: 6 }).notNull(),
    sessionToken: string("sessionToken").notNull(),
    createdAt: datetime("created_at").notNull(),
    updatedAt: datetime("updated_at").notNull(),
  },
  (sessions) => ({
    sessionToken: uniqueIndex("sessionToken").on(sessions.sessionToken),
    userId: index("user_id").on(sessions.userId),
  })
);

export const verificationTokens = mysqlTable("verification_tokens", {
  identifier: string("identifier").notNull(),
  token: string("token").notNull().primaryKey(),
  expires: datetime("expires").notNull(),
  createdAt: datetime("created_at").notNull(),
  updatedAt: datetime("updated_at").notNull(),
});
```
and here's the current deployed sql schema:
```sql
CREATE TABLE `Account` (
	`userId` varchar(191) NOT NULL,
	`type` varchar(191) NOT NULL,
	`provider` varchar(191) NOT NULL,
	`providerAccountId` varchar(191) NOT NULL,
	`refresh_token` text,
	`access_token` text,
	`expires_at` int,
	`token_type` varchar(191),
	`scope` varchar(191),
	`id_token` text,
	`session_state` varchar(191),
	PRIMARY KEY (`provider`, `providerAccountId`),
	KEY `Account_userId_idx` (`userId`)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Recipe` (
	`id` varchar(191) NOT NULL,
	`authorId` varchar(191) NOT NULL,
	`title` varchar(191) NOT NULL,
	`status` enum('DRAFT', 'PUBLISHED') NOT NULL DEFAULT 'DRAFT',
	PRIMARY KEY (`id`),
	KEY `Recipe_authorId_idx` (`authorId`)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Session` (
	`sessionToken` varchar(191) NOT NULL,
	`userId` varchar(191) NOT NULL,
	`expires` datetime(3) NOT NULL,
	UNIQUE KEY `Session_sessionToken_key` (`sessionToken`),
	KEY `Session_userId_idx` (`userId`)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COLLATE utf8mb4_unicode_ci;

CREATE TABLE `User` (
	`id` varchar(191) NOT NULL,
	`name` varchar(191),
	`email` varchar(191) NOT NULL,
	`emailVerified` datetime(3),
	`image` varchar(191),
	PRIMARY KEY (`id`),
	UNIQUE KEY `User_email_key` (`email`)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COLLATE utf8mb4_unicode_ci;

CREATE TABLE `VerificationToken` (
	`identifier` varchar(191) NOT NULL,
	`token` varchar(191) NOT NULL,
	`expires` datetime(3) NOT NULL,
	PRIMARY KEY (`identifier`, `token`),
	UNIQUE KEY `VerificationToken_token_key` (`token`)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COLLATE utf8mb4_unicode_ci;
```

**Comment by natedunn** [comment]
Feels like #170 is related, though I am personally using `push` instead of `generate` for migration. I believe I see the error when I rename a table that has a composite key on it.

**Comment by alextana** [comment]
I am also getting this when renaming a table that has a composite key in it

**Comment by WolfgangVing** [comment]
I got the same error though was for another change and tried to migrate instead of pushing.
Though for me using push it pushed to the dev branch, it didn't alter the tables name but it added instead.

Below is the CLI operations selected from drizzle-kit.

```shell
npm run generate

\> peca-aqui-app@0.1.0 generate
\> drizzle-kit generate:mysql

drizzle-kit: v0.20.10
drizzle-orm: v0.29.3

No config path provided, using default 'drizzle.config.ts'
Reading config file '/home/yuri-css/Documents/peca-aqui-app/drizzle.config.ts'
Reading schema files:
/home/yuri-css/Documents/peca-aqui-app/src/server/db/schema.ts

~ peca-aqui-app_account › account table will be renamed
~ peca-aqui-app_post › post table will be renamed
~ peca-aqui-app_session › session table will be renamed
~ peca-aqui-app_user › user table will be renamed
~ peca-aqui-app_verificationToken › verificationToken table will be renamed
--- all table conflicts resolved ---
```

And this was the error thrown
```TypeError: Cannot read properties of undefined (reading 'compositePrimaryKeys')
    at ./node_modules/drizzle-kit/bin.cjs:17175:51
    at Array.map (<anonymous>)
    at prepareDeleteCompositePrimaryKeyMySql (./node_modules/drizzle-kit/bin.cjs:17170:33)
    at ./node_modules/drizzle-kit/bin.cjs:17560:33
    at Array.forEach (<anonymous>)
    at applySnapshotsDiff (./node_modules/drizzle-kit/bin.cjs:17488:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async prepareSQL (./node_modules/drizzle-kit/bin.cjs:15055:14)
    at async prepareAndMigrateMySql (./node_modules/drizzle-kit/bin.cjs:14953:42)
    at async Command.<anonymous> (./node_modules/drizzle-kit/bin.cjs:63028:3)```

**Comment by L-Mario564** [comment]
Closing in favor of https://github.com/drizzle-team/drizzle-orm/issues/2344 over on the main repo.
