### ISSUE TITLE
Can not do initial push to Planetscale.

### ISSUE THREAD

**Issue by dakamojo** [drizzle-team/drizzle-kit-mirror#77]
Here is my config ts

```
import type {Config} from "drizzle-kit";

export default {
  connectionString: 'mysql://rgxrevhcpsfx7txn1id9:*****@aws.connect.psdb.cloud/akamojo_apps?sslaccept={rejectUnauthorized:true}',
  out: "./migrations",
  schema: "./lib/schema.ts",
  breakpoints: false

} satisfies Config;
```

My push script

```
"pushdb": "drizzle-kit push:mysql"
```

When I run npm run pushdb I get this

```
drizzle-kit: v0.18.1
drizzle-orm: v0.26.3

No config path provided, using default 'drizzle.config.ts'
Reading config file '/Users/darrelldavis/Development/react/sudoku/drizzle.config.ts'
Ignoring invalid configuration option passed to Connection: sslaccept. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Error: unknown error: Code: UNAVAILABLE
server does not allow insecure connections, client must use SSL/TLS

    at createConnection2 (/Users/darrelldavis/Development/react/sudoku/node_modules/drizzle-kit/index.js:43763:35)
    at connectToMySQL (/Users/darrelldavis/Development/react/sudoku/node_modules/drizzle-kit/index.js:45553:60)
    at Command2.<anonymous> (/Users/darrelldavis/Development/react/sudoku/node_modules/drizzle-kit/index.js:51266:28)
    at Command2.listener [as _actionHandler] (/Users/darrelldavis/Development/react/sudoku/node_modules/drizzle-kit/index.js:832:21)
    at /Users/darrelldavis/Development/react/sudoku/node_modules/drizzle-kit/index.js:1251:69
    at Command2._chainOrCall (/Users/darrelldavis/Development/react/sudoku/node_modules/drizzle-kit/index.js:1183:16)
    at Command2._parseCommand (/Users/darrelldavis/Development/react/sudoku/node_modules/drizzle-kit/index.js:1251:31)
    at /Users/darrelldavis/Development/react/sudoku/node_modules/drizzle-kit/index.js:1120:31
    at Command2._chainOrCall (/Users/darrelldavis/Development/react/sudoku/node_modules/drizzle-kit/index.js:1183:16)
    at Command2._dispatchSubcommand (/Users/darrelldavis/Development/react/sudoku/node_modules/drizzle-kit/index.js:1116:27) {
  code: 'ER_UNKNOWN_ERROR',
  errno: 1105,
  sqlState: 'HY000'
}

Node.js v17.0.1
```

It seems sslaccept is not expected.  I tried removing the sslaccept.  I no longer get the message about an unknown parameter, but I do still get the error that the client must use SSL/TLS.

Is this a problem with my MySQL2 driver?  Should this driver even be used with Planetscale?

**Comment by MkrierPharmanity** [comment]
hello
here is a correct connectionString 

 "connectionString": "mysql://username:pscale_password@aws.connect.psdb.cloud/db_name?ssl={\"rejectUnauthorized\":\"true\"}"

**Comment by dakamojo** [comment]
Thanks.  Changed acceptssl to ssl and added the quotes.  That resolved it.
