### ISSUE TITLE
[REQUEST] Allow full paths when specifying schema/out paths in config

### ISSUE THREAD

**Issue by Sandy-Garrido** [drizzle-team/drizzle-kit-mirror#87]
### Request Context
Hi there, I recently ran into when setting my schema and out paths in config, however, I noticed that it automatically just prepends my path with `./` meaning that any full path I provide will be incorrect.

My request is fairly simple. Could we check if the given path starts with `/` before prepending it with `./`? 

I'd add it myself but, not open source :P 

### Example config

```Typescript
import type { Config } from "drizzle-kit";
import path from "path";

export default {
	schema: path.join(__dirname, "schema.ts"),
	out: path.join(__dirname, "migrations"),
} satisfies Config;
```

### Observed Error

```bash
(22:26:13)root@wsl:/workspaces/my-app$ yarn db:generate
drizzle-kit: v0.18.1
drizzle-orm: v0.26.5

Reading config file '/workspaces/my-app/app/database/drizzle.config.ts'
Error: ENOENT: no such file or directory, open './/workspaces/my-app/app/database/migrations/meta/0000_snapshot.json'
    at Object.openSync (node:fs:601:3)
    at readFileSync (node:fs:469:35)
    at snapshots.reduce.malformed (/workspaces/my-app/node_modules/drizzle-kit/index.js:27412:62)
    at Array.reduce (<anonymous>)
    at validateWithReport (/workspaces/my-app/node_modules/drizzle-kit/index.js:27409:32)
    at prepareMigrationFolder (/workspaces/my-app/node_modules/drizzle-kit/index.js:27452:22)
    at prepareAndMigrateMySql (/workspaces/my-app/node_modules/drizzle-kit/index.js:23904:40)
    at Command2.<anonymous> (/workspaces/my-app/node_modules/drizzle-kit/index.js:51221:9)
    at Command2.listener [as _actionHandler] (/workspaces/my-app/node_modules/drizzle-kit/index.js:832:21)
    at /workspaces/my-app/node_modules/drizzle-kit/index.js:1251:69 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './/workspaces/my-app/app/database/migrations/meta/0000_snapshot.json'
}
```

**Comment by namdien177** [comment]
seems like the team is working on [this issue (as it was assigned)](https://github.com/drizzle-team/drizzle-kit-mirror/issues/81)

**Comment by Sandy-Garrido** [comment]
> seems like the team is working on [this issue (as it was assigned)](https://github.com/drizzle-team/drizzle-kit-mirror/issues/81)

Gah, I missed this when searching! Guess we can close this duplicate then!
